// secsy-pki gRPC API surface (Task 56).
//
// This service exposes the core PKI operations — issue, renew, revoke, and
// status/metadata lookups — alongside the existing REST API. It is a thin
// transport over the same ca.Manager / RBAC / audit / rate-limit / tracing
// plumbing that backs REST, so both protocols enforce identical authorization,
// tenant scoping, and audit semantics.
//
// Authentication mirrors REST: an `authorization` request-metadata header
// (Basic root credentials or a Bearer OIDC token) and/or a mutual-TLS client
// certificate bound to an operator principal. Errors map to canonical gRPC
// status codes (see the service comments). Request IDs and W3C trace context
// propagate through call metadata.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pki/v1/pki.proto

package pkiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CertificateStatus is the coarse lifecycle state of an issued certificate.
type CertificateStatus int32

const (
	CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED CertificateStatus = 0
	CertificateStatus_CERTIFICATE_STATUS_VALID       CertificateStatus = 1
	CertificateStatus_CERTIFICATE_STATUS_EXPIRED     CertificateStatus = 2
	CertificateStatus_CERTIFICATE_STATUS_REVOKED     CertificateStatus = 3
	// The authority has no record of this serial under the named CA.
	CertificateStatus_CERTIFICATE_STATUS_UNKNOWN CertificateStatus = 4
)

// Enum value maps for CertificateStatus.
var (
	CertificateStatus_name = map[int32]string{
		0: "CERTIFICATE_STATUS_UNSPECIFIED",
		1: "CERTIFICATE_STATUS_VALID",
		2: "CERTIFICATE_STATUS_EXPIRED",
		3: "CERTIFICATE_STATUS_REVOKED",
		4: "CERTIFICATE_STATUS_UNKNOWN",
	}
	CertificateStatus_value = map[string]int32{
		"CERTIFICATE_STATUS_UNSPECIFIED": 0,
		"CERTIFICATE_STATUS_VALID":       1,
		"CERTIFICATE_STATUS_EXPIRED":     2,
		"CERTIFICATE_STATUS_REVOKED":     3,
		"CERTIFICATE_STATUS_UNKNOWN":     4,
	}
)

func (x CertificateStatus) Enum() *CertificateStatus {
	p := new(CertificateStatus)
	*p = x
	return p
}

func (x CertificateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pki_v1_pki_proto_enumTypes[0].Descriptor()
}

func (CertificateStatus) Type() protoreflect.EnumType {
	return &file_pki_v1_pki_proto_enumTypes[0]
}

func (x CertificateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateStatus.Descriptor instead.
func (CertificateStatus) EnumDescriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{0}
}

// CTLogOutcome reports the per-log result of a Certificate Transparency
// submission for an issuance.
type CTLogOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTLogOutcome) Reset() {
	*x = CTLogOutcome{}
	mi := &file_pki_v1_pki_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTLogOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTLogOutcome) ProtoMessage() {}

func (x *CTLogOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTLogOutcome.ProtoReflect.Descriptor instead.
func (*CTLogOutcome) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{0}
}

func (x *CTLogOutcome) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *CTLogOutcome) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CTLogOutcome) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CTInfo summarizes Certificate Transparency handling for an issuance. Present
// only when the profile requested CT.
type CTInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Embedded      bool                   `protobuf:"varint,2,opt,name=embedded,proto3" json:"embedded,omitempty"`
	SctCount      int32                  `protobuf:"varint,3,opt,name=sct_count,json=sctCount,proto3" json:"sct_count,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Logs          []*CTLogOutcome        `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTInfo) Reset() {
	*x = CTInfo{}
	mi := &file_pki_v1_pki_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTInfo) ProtoMessage() {}

func (x *CTInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTInfo.ProtoReflect.Descriptor instead.
func (*CTInfo) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{1}
}

func (x *CTInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CTInfo) GetEmbedded() bool {
	if x != nil {
		return x.Embedded
	}
	return false
}

func (x *CTInfo) GetSctCount() int32 {
	if x != nil {
		return x.SctCount
	}
	return 0
}

func (x *CTInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CTInfo) GetLogs() []*CTLogOutcome {
	if x != nil {
		return x.Logs
	}
	return nil
}

type IssueCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ca_id identifies the issuing CA. It must be an X.509 issuer.
	CaId string `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	// csr_pem is a PEM-encoded PKCS#10 certificate signing request.
	CsrPem string `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// profile is the certificate profile name; empty selects the default profile.
	Profile string `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	// validity_days overrides the profile default. Non-positive uses the default;
	// it is always clamped to the profile maximum, the CA expiry, and any global
	// policy cap.
	ValidityDays  int32 `protobuf:"varint,4,opt,name=validity_days,json=validityDays,proto3" json:"validity_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCertificateRequest) Reset() {
	*x = IssueCertificateRequest{}
	mi := &file_pki_v1_pki_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCertificateRequest) ProtoMessage() {}

func (x *IssueCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCertificateRequest.ProtoReflect.Descriptor instead.
func (*IssueCertificateRequest) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{2}
}

func (x *IssueCertificateRequest) GetCaId() string {
	if x != nil {
		return x.CaId
	}
	return ""
}

func (x *IssueCertificateRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *IssueCertificateRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *IssueCertificateRequest) GetValidityDays() int32 {
	if x != nil {
		return x.ValidityDays
	}
	return 0
}

type RenewCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	CaId  string                 `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	// serial is the decimal serial of the certificate to renew.
	Serial string `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	// csr_pem optionally rekeys the certificate; empty reuses the original key.
	CsrPem        string `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	ValidityDays  int32  `protobuf:"varint,4,opt,name=validity_days,json=validityDays,proto3" json:"validity_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateRequest) Reset() {
	*x = RenewCertificateRequest{}
	mi := &file_pki_v1_pki_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateRequest) ProtoMessage() {}

func (x *RenewCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewCertificateRequest) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{3}
}

func (x *RenewCertificateRequest) GetCaId() string {
	if x != nil {
		return x.CaId
	}
	return ""
}

func (x *RenewCertificateRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RenewCertificateRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *RenewCertificateRequest) GetValidityDays() int32 {
	if x != nil {
		return x.ValidityDays
	}
	return 0
}

// CertificateResponse is a freshly issued or renewed end-entity certificate.
type CertificateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem string                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	ChainPem       string                 `protobuf:"bytes,2,opt,name=chain_pem,json=chainPem,proto3" json:"chain_pem,omitempty"`
	Serial         string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Profile        string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	NotBefore      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Ct             *CTInfo                `protobuf:"bytes,7,opt,name=ct,proto3" json:"ct,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_pki_v1_pki_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{4}
}

func (x *CertificateResponse) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *CertificateResponse) GetChainPem() string {
	if x != nil {
		return x.ChainPem
	}
	return ""
}

func (x *CertificateResponse) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *CertificateResponse) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *CertificateResponse) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertificateResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertificateResponse) GetCt() *CTInfo {
	if x != nil {
		return x.Ct
	}
	return nil
}

type RevokeCertificateRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CaId   string                 `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	Serial string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	// reason is an RFC 5280 CRL reason name (e.g. "keyCompromise",
	// "cessationOfOperation"); empty defaults to "unspecified".
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateRequest) Reset() {
	*x = RevokeCertificateRequest{}
	mi := &file_pki_v1_pki_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateRequest) ProtoMessage() {}

func (x *RevokeCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateRequest.ProtoReflect.Descriptor instead.
func (*RevokeCertificateRequest) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeCertificateRequest) GetCaId() string {
	if x != nil {
		return x.CaId
	}
	return ""
}

func (x *RevokeCertificateRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RevokeCertificateRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeCertificateResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Serial string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	// status is "revoked" for a newly applied revocation or "already-revoked"
	// when the serial was already revoked (idempotent).
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateResponse) Reset() {
	*x = RevokeCertificateResponse{}
	mi := &file_pki_v1_pki_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateResponse) ProtoMessage() {}

func (x *RevokeCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateResponse.ProtoReflect.Descriptor instead.
func (*RevokeCertificateResponse) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeCertificateResponse) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RevokeCertificateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// CertificateInfo is the authority's stored view of a certificate it issued.
type CertificateInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CaId             string                 `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	Serial           string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Subject          string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	CommonName       string                 `protobuf:"bytes,4,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Sans             []string               `protobuf:"bytes,5,rep,name=sans,proto3" json:"sans,omitempty"`
	Profile          string                 `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	CertificatePem   string                 `protobuf:"bytes,7,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	NotBefore        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Status           CertificateStatus      `protobuf:"varint,10,opt,name=status,proto3,enum=secsy.pki.v1.CertificateStatus" json:"status,omitempty"`
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	RevocationReason int32                  `protobuf:"varint,12,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
	RequestedBy      string                 `protobuf:"bytes,13,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CertificateInfo) Reset() {
	*x = CertificateInfo{}
	mi := &file_pki_v1_pki_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateInfo) ProtoMessage() {}

func (x *CertificateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateInfo.ProtoReflect.Descriptor instead.
func (*CertificateInfo) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{7}
}

func (x *CertificateInfo) GetCaId() string {
	if x != nil {
		return x.CaId
	}
	return ""
}

func (x *CertificateInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *CertificateInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CertificateInfo) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *CertificateInfo) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *CertificateInfo) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *CertificateInfo) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *CertificateInfo) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertificateInfo) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertificateInfo) GetStatus() CertificateStatus {
	if x != nil {
		return x.Status
	}
	return CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED
}

func (x *CertificateInfo) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *CertificateInfo) GetRevocationReason() int32 {
	if x != nil {
		return x.RevocationReason
	}
	return 0
}

func (x *CertificateInfo) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *CertificateInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaId          string                 `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	mi := &file_pki_v1_pki_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{8}
}

func (x *GetCertificateRequest) GetCaId() string {
	if x != nil {
		return x.CaId
	}
	return ""
}

func (x *GetCertificateRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type GetCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *CertificateInfo       `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateResponse) Reset() {
	*x = GetCertificateResponse{}
	mi := &file_pki_v1_pki_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateResponse) ProtoMessage() {}

func (x *GetCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateResponse) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{9}
}

func (x *GetCertificateResponse) GetCertificate() *CertificateInfo {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type GetCertificateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaId          string                 `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateStatusRequest) Reset() {
	*x = GetCertificateStatusRequest{}
	mi := &file_pki_v1_pki_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateStatusRequest) ProtoMessage() {}

func (x *GetCertificateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateStatusRequest) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{10}
}

func (x *GetCertificateStatusRequest) GetCaId() string {
	if x != nil {
		return x.CaId
	}
	return ""
}

func (x *GetCertificateStatusRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type GetCertificateStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           CertificateStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=secsy.pki.v1.CertificateStatus" json:"status,omitempty"`
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	RevocationReason int32                  `protobuf:"varint,3,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCertificateStatusResponse) Reset() {
	*x = GetCertificateStatusResponse{}
	mi := &file_pki_v1_pki_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateStatusResponse) ProtoMessage() {}

func (x *GetCertificateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateStatusResponse) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{11}
}

func (x *GetCertificateStatusResponse) GetStatus() CertificateStatus {
	if x != nil {
		return x.Status
	}
	return CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED
}

func (x *GetCertificateStatusResponse) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *GetCertificateStatusResponse) GetRevocationReason() int32 {
	if x != nil {
		return x.RevocationReason
	}
	return 0
}

type ListCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaId          string                 `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesRequest) Reset() {
	*x = ListCertificatesRequest{}
	mi := &file_pki_v1_pki_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesRequest) ProtoMessage() {}

func (x *ListCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesRequest.ProtoReflect.Descriptor instead.
func (*ListCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{12}
}

func (x *ListCertificatesRequest) GetCaId() string {
	if x != nil {
		return x.CaId
	}
	return ""
}

type ListCertificatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*CertificateInfo     `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesResponse) Reset() {
	*x = ListCertificatesResponse{}
	mi := &file_pki_v1_pki_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesResponse) ProtoMessage() {}

func (x *ListCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesResponse.ProtoReflect.Descriptor instead.
func (*ListCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{13}
}

func (x *ListCertificatesResponse) GetCertificates() []*CertificateInfo {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type GetCRLMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	CaId  string                 `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	// shard, when set, selects a CRL partition (0..shard_count-1). When unset the
	// full (unsharded) CRL is described. Sharding must be enabled to name a shard.
	Shard         *int32 `protobuf:"varint,2,opt,name=shard,proto3,oneof" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLMetadataRequest) Reset() {
	*x = GetCRLMetadataRequest{}
	mi := &file_pki_v1_pki_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLMetadataRequest) ProtoMessage() {}

func (x *GetCRLMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetCRLMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{14}
}

func (x *GetCRLMetadataRequest) GetCaId() string {
	if x != nil {
		return x.CaId
	}
	return ""
}

func (x *GetCRLMetadataRequest) GetShard() int32 {
	if x != nil && x.Shard != nil {
		return *x.Shard
	}
	return 0
}

type GetCRLMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scope is "full" for the unsharded CRL or "partition:N" for a shard.
	Scope       string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	CrlNumber   int64                  `protobuf:"varint,2,opt,name=crl_number,json=crlNumber,proto3" json:"crl_number,omitempty"`
	ThisUpdate  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=this_update,json=thisUpdate,proto3" json:"this_update,omitempty"`
	NextUpdate  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_update,json=nextUpdate,proto3" json:"next_update,omitempty"`
	CrlUrl      string                 `protobuf:"bytes,5,opt,name=crl_url,json=crlUrl,proto3" json:"crl_url,omitempty"`
	DeltaCrlUrl string                 `protobuf:"bytes,6,opt,name=delta_crl_url,json=deltaCrlUrl,proto3" json:"delta_crl_url,omitempty"`
	// delta_available is true when a delta CRL has been published for this scope.
	DeltaAvailable  bool                   `protobuf:"varint,7,opt,name=delta_available,json=deltaAvailable,proto3" json:"delta_available,omitempty"`
	DeltaCrlNumber  int64                  `protobuf:"varint,8,opt,name=delta_crl_number,json=deltaCrlNumber,proto3" json:"delta_crl_number,omitempty"`
	DeltaThisUpdate *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=delta_this_update,json=deltaThisUpdate,proto3" json:"delta_this_update,omitempty"`
	DeltaNextUpdate *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=delta_next_update,json=deltaNextUpdate,proto3" json:"delta_next_update,omitempty"`
	// shard_count is the configured number of CRL partitions (0/1 = unsharded).
	ShardCount    int32 `protobuf:"varint,11,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLMetadataResponse) Reset() {
	*x = GetCRLMetadataResponse{}
	mi := &file_pki_v1_pki_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLMetadataResponse) ProtoMessage() {}

func (x *GetCRLMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetCRLMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{15}
}

func (x *GetCRLMetadataResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetCRLMetadataResponse) GetCrlNumber() int64 {
	if x != nil {
		return x.CrlNumber
	}
	return 0
}

func (x *GetCRLMetadataResponse) GetThisUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.ThisUpdate
	}
	return nil
}

func (x *GetCRLMetadataResponse) GetNextUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextUpdate
	}
	return nil
}

func (x *GetCRLMetadataResponse) GetCrlUrl() string {
	if x != nil {
		return x.CrlUrl
	}
	return ""
}

func (x *GetCRLMetadataResponse) GetDeltaCrlUrl() string {
	if x != nil {
		return x.DeltaCrlUrl
	}
	return ""
}

func (x *GetCRLMetadataResponse) GetDeltaAvailable() bool {
	if x != nil {
		return x.DeltaAvailable
	}
	return false
}

func (x *GetCRLMetadataResponse) GetDeltaCrlNumber() int64 {
	if x != nil {
		return x.DeltaCrlNumber
	}
	return 0
}

func (x *GetCRLMetadataResponse) GetDeltaThisUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeltaThisUpdate
	}
	return nil
}

func (x *GetCRLMetadataResponse) GetDeltaNextUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeltaNextUpdate
	}
	return nil
}

func (x *GetCRLMetadataResponse) GetShardCount() int32 {
	if x != nil {
		return x.ShardCount
	}
	return 0
}

type GetOCSPMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaId          string                 `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOCSPMetadataRequest) Reset() {
	*x = GetOCSPMetadataRequest{}
	mi := &file_pki_v1_pki_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOCSPMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOCSPMetadataRequest) ProtoMessage() {}

func (x *GetOCSPMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOCSPMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetOCSPMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{16}
}

func (x *GetOCSPMetadataRequest) GetCaId() string {
	if x != nil {
		return x.CaId
	}
	return ""
}

type GetOCSPMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ocsp_urls are the responder endpoint(s) for this CA. Empty when no public
	// base URL is configured (crl.base_url / acme.base_url).
	OcspUrls []string `protobuf:"bytes,1,rep,name=ocsp_urls,json=ocspUrls,proto3" json:"ocsp_urls,omitempty"`
	// nonce_supported reports whether the responder echoes RFC 8954 nonces.
	NonceSupported bool `protobuf:"varint,2,opt,name=nonce_supported,json=nonceSupported,proto3" json:"nonce_supported,omitempty"`
	// delegated_responder reports whether responses are signed by a short-lived
	// delegated OCSP-signing certificate rather than the CA key.
	DelegatedResponder bool `protobuf:"varint,3,opt,name=delegated_responder,json=delegatedResponder,proto3" json:"delegated_responder,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetOCSPMetadataResponse) Reset() {
	*x = GetOCSPMetadataResponse{}
	mi := &file_pki_v1_pki_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOCSPMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOCSPMetadataResponse) ProtoMessage() {}

func (x *GetOCSPMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pki_v1_pki_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOCSPMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetOCSPMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pki_v1_pki_proto_rawDescGZIP(), []int{17}
}

func (x *GetOCSPMetadataResponse) GetOcspUrls() []string {
	if x != nil {
		return x.OcspUrls
	}
	return nil
}

func (x *GetOCSPMetadataResponse) GetNonceSupported() bool {
	if x != nil {
		return x.NonceSupported
	}
	return false
}

func (x *GetOCSPMetadataResponse) GetDelegatedResponder() bool {
	if x != nil {
		return x.DelegatedResponder
	}
	return false
}

var File_pki_v1_pki_proto protoreflect.FileDescriptor

const file_pki_v1_pki_proto_rawDesc = "" +
	"\n" +
	"\x10pki/v1/pki.proto\x12\fsecsy.pki.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\fCTLogOutcome\x12\x10\n" +
	"\x03log\x18\x01 \x01(\tR\x03log\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa3\x01\n" +
	"\x06CTInfo\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bembedded\x18\x02 \x01(\bR\bembedded\x12\x1b\n" +
	"\tsct_count\x18\x03 \x01(\x05R\bsctCount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12.\n" +
	"\x04logs\x18\x05 \x03(\v2\x1a.secsy.pki.v1.CTLogOutcomeR\x04logs\"\x86\x01\n" +
	"\x17IssueCertificateRequest\x12\x13\n" +
	"\x05ca_id\x18\x01 \x01(\tR\x04caId\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\tR\x06csrPem\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x12#\n" +
	"\rvalidity_days\x18\x04 \x01(\x05R\fvalidityDays\"\x84\x01\n" +
	"\x17RenewCertificateRequest\x12\x13\n" +
	"\x05ca_id\x18\x01 \x01(\tR\x04caId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\tR\x06csrPem\x12#\n" +
	"\rvalidity_days\x18\x04 \x01(\x05R\fvalidityDays\"\xa7\x02\n" +
	"\x13CertificateResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\tR\x0ecertificatePem\x12\x1b\n" +
	"\tchain_pem\x18\x02 \x01(\tR\bchainPem\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x129\n" +
	"\n" +
	"not_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12$\n" +
	"\x02ct\x18\a \x01(\v2\x14.secsy.pki.v1.CTInfoR\x02ct\"_\n" +
	"\x18RevokeCertificateRequest\x12\x13\n" +
	"\x05ca_id\x18\x01 \x01(\tR\x04caId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"K\n" +
	"\x19RevokeCertificateResponse\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xc3\x04\n" +
	"\x0fCertificateInfo\x12\x13\n" +
	"\x05ca_id\x18\x01 \x01(\tR\x04caId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1f\n" +
	"\vcommon_name\x18\x04 \x01(\tR\n" +
	"commonName\x12\x12\n" +
	"\x04sans\x18\x05 \x03(\tR\x04sans\x12\x18\n" +
	"\aprofile\x18\x06 \x01(\tR\aprofile\x12'\n" +
	"\x0fcertificate_pem\x18\a \x01(\tR\x0ecertificatePem\x129\n" +
	"\n" +
	"not_before\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x127\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x1f.secsy.pki.v1.CertificateStatusR\x06status\x129\n" +
	"\n" +
	"revoked_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12+\n" +
	"\x11revocation_reason\x18\f \x01(\x05R\x10revocationReason\x12!\n" +
	"\frequested_by\x18\r \x01(\tR\vrequestedBy\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"D\n" +
	"\x15GetCertificateRequest\x12\x13\n" +
	"\x05ca_id\x18\x01 \x01(\tR\x04caId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\"Y\n" +
	"\x16GetCertificateResponse\x12?\n" +
	"\vcertificate\x18\x01 \x01(\v2\x1d.secsy.pki.v1.CertificateInfoR\vcertificate\"J\n" +
	"\x1bGetCertificateStatusRequest\x12\x13\n" +
	"\x05ca_id\x18\x01 \x01(\tR\x04caId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\"\xbf\x01\n" +
	"\x1cGetCertificateStatusResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.secsy.pki.v1.CertificateStatusR\x06status\x129\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12+\n" +
	"\x11revocation_reason\x18\x03 \x01(\x05R\x10revocationReason\".\n" +
	"\x17ListCertificatesRequest\x12\x13\n" +
	"\x05ca_id\x18\x01 \x01(\tR\x04caId\"]\n" +
	"\x18ListCertificatesResponse\x12A\n" +
	"\fcertificates\x18\x01 \x03(\v2\x1d.secsy.pki.v1.CertificateInfoR\fcertificates\"Q\n" +
	"\x15GetCRLMetadataRequest\x12\x13\n" +
	"\x05ca_id\x18\x01 \x01(\tR\x04caId\x12\x19\n" +
	"\x05shard\x18\x02 \x01(\x05H\x00R\x05shard\x88\x01\x01B\b\n" +
	"\x06_shard\"\x88\x04\n" +
	"\x16GetCRLMetadataResponse\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"crl_number\x18\x02 \x01(\x03R\tcrlNumber\x12;\n" +
	"\vthis_update\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"thisUpdate\x12;\n" +
	"\vnext_update\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"nextUpdate\x12\x17\n" +
	"\acrl_url\x18\x05 \x01(\tR\x06crlUrl\x12\"\n" +
	"\rdelta_crl_url\x18\x06 \x01(\tR\vdeltaCrlUrl\x12'\n" +
	"\x0fdelta_available\x18\a \x01(\bR\x0edeltaAvailable\x12(\n" +
	"\x10delta_crl_number\x18\b \x01(\x03R\x0edeltaCrlNumber\x12F\n" +
	"\x11delta_this_update\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0fdeltaThisUpdate\x12F\n" +
	"\x11delta_next_update\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0fdeltaNextUpdate\x12\x1f\n" +
	"\vshard_count\x18\v \x01(\x05R\n" +
	"shardCount\"-\n" +
	"\x16GetOCSPMetadataRequest\x12\x13\n" +
	"\x05ca_id\x18\x01 \x01(\tR\x04caId\"\x90\x01\n" +
	"\x17GetOCSPMetadataResponse\x12\x1b\n" +
	"\tocsp_urls\x18\x01 \x03(\tR\bocspUrls\x12'\n" +
	"\x0fnonce_supported\x18\x02 \x01(\bR\x0enonceSupported\x12/\n" +
	"\x13delegated_responder\x18\x03 \x01(\bR\x12delegatedResponder*\xb5\x01\n" +
	"\x11CertificateStatus\x12\"\n" +
	"\x1eCERTIFICATE_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CERTIFICATE_STATUS_VALID\x10\x01\x12\x1e\n" +
	"\x1aCERTIFICATE_STATUS_EXPIRED\x10\x02\x12\x1e\n" +
	"\x1aCERTIFICATE_STATUS_REVOKED\x10\x03\x12\x1e\n" +
	"\x1aCERTIFICATE_STATUS_UNKNOWN\x10\x042\x9a\x06\n" +
	"\n" +
	"PKIService\x12\\\n" +
	"\x10IssueCertificate\x12%.secsy.pki.v1.IssueCertificateRequest\x1a!.secsy.pki.v1.CertificateResponse\x12\\\n" +
	"\x10RenewCertificate\x12%.secsy.pki.v1.RenewCertificateRequest\x1a!.secsy.pki.v1.CertificateResponse\x12d\n" +
	"\x11RevokeCertificate\x12&.secsy.pki.v1.RevokeCertificateRequest\x1a'.secsy.pki.v1.RevokeCertificateResponse\x12[\n" +
	"\x0eGetCertificate\x12#.secsy.pki.v1.GetCertificateRequest\x1a$.secsy.pki.v1.GetCertificateResponse\x12m\n" +
	"\x14GetCertificateStatus\x12).secsy.pki.v1.GetCertificateStatusRequest\x1a*.secsy.pki.v1.GetCertificateStatusResponse\x12a\n" +
	"\x10ListCertificates\x12%.secsy.pki.v1.ListCertificatesRequest\x1a&.secsy.pki.v1.ListCertificatesResponse\x12[\n" +
	"\x0eGetCRLMetadata\x12#.secsy.pki.v1.GetCRLMetadataRequest\x1a$.secsy.pki.v1.GetCRLMetadataResponse\x12^\n" +
	"\x0fGetOCSPMetadata\x12$.secsy.pki.v1.GetOCSPMetadataRequest\x1a%.secsy.pki.v1.GetOCSPMetadataResponseBGZEgithub.com/blechschmidt/secsy-pki/server/internal/grpcapi/pkiv1;pkiv1b\x06proto3"

var (
	file_pki_v1_pki_proto_rawDescOnce sync.Once
	file_pki_v1_pki_proto_rawDescData []byte
)

func file_pki_v1_pki_proto_rawDescGZIP() []byte {
	file_pki_v1_pki_proto_rawDescOnce.Do(func() {
		file_pki_v1_pki_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pki_v1_pki_proto_rawDesc), len(file_pki_v1_pki_proto_rawDesc)))
	})
	return file_pki_v1_pki_proto_rawDescData
}

var file_pki_v1_pki_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pki_v1_pki_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pki_v1_pki_proto_goTypes = []any{
	(CertificateStatus)(0),               // 0: secsy.pki.v1.CertificateStatus
	(*CTLogOutcome)(nil),                 // 1: secsy.pki.v1.CTLogOutcome
	(*CTInfo)(nil),                       // 2: secsy.pki.v1.CTInfo
	(*IssueCertificateRequest)(nil),      // 3: secsy.pki.v1.IssueCertificateRequest
	(*RenewCertificateRequest)(nil),      // 4: secsy.pki.v1.RenewCertificateRequest
	(*CertificateResponse)(nil),          // 5: secsy.pki.v1.CertificateResponse
	(*RevokeCertificateRequest)(nil),     // 6: secsy.pki.v1.RevokeCertificateRequest
	(*RevokeCertificateResponse)(nil),    // 7: secsy.pki.v1.RevokeCertificateResponse
	(*CertificateInfo)(nil),              // 8: secsy.pki.v1.CertificateInfo
	(*GetCertificateRequest)(nil),        // 9: secsy.pki.v1.GetCertificateRequest
	(*GetCertificateResponse)(nil),       // 10: secsy.pki.v1.GetCertificateResponse
	(*GetCertificateStatusRequest)(nil),  // 11: secsy.pki.v1.GetCertificateStatusRequest
	(*GetCertificateStatusResponse)(nil), // 12: secsy.pki.v1.GetCertificateStatusResponse
	(*ListCertificatesRequest)(nil),      // 13: secsy.pki.v1.ListCertificatesRequest
	(*ListCertificatesResponse)(nil),     // 14: secsy.pki.v1.ListCertificatesResponse
	(*GetCRLMetadataRequest)(nil),        // 15: secsy.pki.v1.GetCRLMetadataRequest
	(*GetCRLMetadataResponse)(nil),       // 16: secsy.pki.v1.GetCRLMetadataResponse
	(*GetOCSPMetadataRequest)(nil),       // 17: secsy.pki.v1.GetOCSPMetadataRequest
	(*GetOCSPMetadataResponse)(nil),      // 18: secsy.pki.v1.GetOCSPMetadataResponse
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
}
var file_pki_v1_pki_proto_depIdxs = []int32{
	1,  // 0: secsy.pki.v1.CTInfo.logs:type_name -> secsy.pki.v1.CTLogOutcome
	19, // 1: secsy.pki.v1.CertificateResponse.not_before:type_name -> google.protobuf.Timestamp
	19, // 2: secsy.pki.v1.CertificateResponse.not_after:type_name -> google.protobuf.Timestamp
	2,  // 3: secsy.pki.v1.CertificateResponse.ct:type_name -> secsy.pki.v1.CTInfo
	19, // 4: secsy.pki.v1.CertificateInfo.not_before:type_name -> google.protobuf.Timestamp
	19, // 5: secsy.pki.v1.CertificateInfo.not_after:type_name -> google.protobuf.Timestamp
	0,  // 6: secsy.pki.v1.CertificateInfo.status:type_name -> secsy.pki.v1.CertificateStatus
	19, // 7: secsy.pki.v1.CertificateInfo.revoked_at:type_name -> google.protobuf.Timestamp
	19, // 8: secsy.pki.v1.CertificateInfo.created_at:type_name -> google.protobuf.Timestamp
	8,  // 9: secsy.pki.v1.GetCertificateResponse.certificate:type_name -> secsy.pki.v1.CertificateInfo
	0,  // 10: secsy.pki.v1.GetCertificateStatusResponse.status:type_name -> secsy.pki.v1.CertificateStatus
	19, // 11: secsy.pki.v1.GetCertificateStatusResponse.revoked_at:type_name -> google.protobuf.Timestamp
	8,  // 12: secsy.pki.v1.ListCertificatesResponse.certificates:type_name -> secsy.pki.v1.CertificateInfo
	19, // 13: secsy.pki.v1.GetCRLMetadataResponse.this_update:type_name -> google.protobuf.Timestamp
	19, // 14: secsy.pki.v1.GetCRLMetadataResponse.next_update:type_name -> google.protobuf.Timestamp
	19, // 15: secsy.pki.v1.GetCRLMetadataResponse.delta_this_update:type_name -> google.protobuf.Timestamp
	19, // 16: secsy.pki.v1.GetCRLMetadataResponse.delta_next_update:type_name -> google.protobuf.Timestamp
	3,  // 17: secsy.pki.v1.PKIService.IssueCertificate:input_type -> secsy.pki.v1.IssueCertificateRequest
	4,  // 18: secsy.pki.v1.PKIService.RenewCertificate:input_type -> secsy.pki.v1.RenewCertificateRequest
	6,  // 19: secsy.pki.v1.PKIService.RevokeCertificate:input_type -> secsy.pki.v1.RevokeCertificateRequest
	9,  // 20: secsy.pki.v1.PKIService.GetCertificate:input_type -> secsy.pki.v1.GetCertificateRequest
	11, // 21: secsy.pki.v1.PKIService.GetCertificateStatus:input_type -> secsy.pki.v1.GetCertificateStatusRequest
	13, // 22: secsy.pki.v1.PKIService.ListCertificates:input_type -> secsy.pki.v1.ListCertificatesRequest
	15, // 23: secsy.pki.v1.PKIService.GetCRLMetadata:input_type -> secsy.pki.v1.GetCRLMetadataRequest
	17, // 24: secsy.pki.v1.PKIService.GetOCSPMetadata:input_type -> secsy.pki.v1.GetOCSPMetadataRequest
	5,  // 25: secsy.pki.v1.PKIService.IssueCertificate:output_type -> secsy.pki.v1.CertificateResponse
	5,  // 26: secsy.pki.v1.PKIService.RenewCertificate:output_type -> secsy.pki.v1.CertificateResponse
	7,  // 27: secsy.pki.v1.PKIService.RevokeCertificate:output_type -> secsy.pki.v1.RevokeCertificateResponse
	10, // 28: secsy.pki.v1.PKIService.GetCertificate:output_type -> secsy.pki.v1.GetCertificateResponse
	12, // 29: secsy.pki.v1.PKIService.GetCertificateStatus:output_type -> secsy.pki.v1.GetCertificateStatusResponse
	14, // 30: secsy.pki.v1.PKIService.ListCertificates:output_type -> secsy.pki.v1.ListCertificatesResponse
	16, // 31: secsy.pki.v1.PKIService.GetCRLMetadata:output_type -> secsy.pki.v1.GetCRLMetadataResponse
	18, // 32: secsy.pki.v1.PKIService.GetOCSPMetadata:output_type -> secsy.pki.v1.GetOCSPMetadataResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pki_v1_pki_proto_init() }
func file_pki_v1_pki_proto_init() {
	if File_pki_v1_pki_proto != nil {
		return
	}
	file_pki_v1_pki_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pki_v1_pki_proto_rawDesc), len(file_pki_v1_pki_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pki_v1_pki_proto_goTypes,
		DependencyIndexes: file_pki_v1_pki_proto_depIdxs,
		EnumInfos:         file_pki_v1_pki_proto_enumTypes,
		MessageInfos:      file_pki_v1_pki_proto_msgTypes,
	}.Build()
	File_pki_v1_pki_proto = out.File
	file_pki_v1_pki_proto_goTypes = nil
	file_pki_v1_pki_proto_depIdxs = nil
}
