// secsy-pki gRPC API surface (Task 56).
//
// This service exposes the core PKI operations — issue, renew, revoke, and
// status/metadata lookups — alongside the existing REST API. It is a thin
// transport over the same ca.Manager / RBAC / audit / rate-limit / tracing
// plumbing that backs REST, so both protocols enforce identical authorization,
// tenant scoping, and audit semantics.
//
// Authentication mirrors REST: an `authorization` request-metadata header
// (Basic root credentials or a Bearer OIDC token) and/or a mutual-TLS client
// certificate bound to an operator principal. Errors map to canonical gRPC
// status codes (see the service comments). Request IDs and W3C trace context
// propagate through call metadata.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pki/v1/pki.proto

package pkiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PKIService_IssueCertificate_FullMethodName     = "/secsy.pki.v1.PKIService/IssueCertificate"
	PKIService_PreviewCertificate_FullMethodName   = "/secsy.pki.v1.PKIService/PreviewCertificate"
	PKIService_ValidateChain_FullMethodName        = "/secsy.pki.v1.PKIService/ValidateChain"
	PKIService_RenewCertificate_FullMethodName     = "/secsy.pki.v1.PKIService/RenewCertificate"
	PKIService_RevokeCertificate_FullMethodName    = "/secsy.pki.v1.PKIService/RevokeCertificate"
	PKIService_SuspendCertificate_FullMethodName   = "/secsy.pki.v1.PKIService/SuspendCertificate"
	PKIService_ReleaseCertificate_FullMethodName   = "/secsy.pki.v1.PKIService/ReleaseCertificate"
	PKIService_GetCertificate_FullMethodName       = "/secsy.pki.v1.PKIService/GetCertificate"
	PKIService_GetCertificateStatus_FullMethodName = "/secsy.pki.v1.PKIService/GetCertificateStatus"
	PKIService_ListCertificates_FullMethodName     = "/secsy.pki.v1.PKIService/ListCertificates"
	PKIService_GetCRLMetadata_FullMethodName       = "/secsy.pki.v1.PKIService/GetCRLMetadata"
	PKIService_GetOCSPMetadata_FullMethodName      = "/secsy.pki.v1.PKIService/GetOCSPMetadata"
	PKIService_StreamEvents_FullMethodName         = "/secsy.pki.v1.PKIService/StreamEvents"
)

// PKIServiceClient is the client API for PKIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PKIService is the certificate-lifecycle gRPC surface. Every RPC authorizes the
// caller against the acting CA's tenant using the same RBAC checks as REST and
// appends a tamper-evident audit event for state-changing operations.
type PKIServiceClient interface {
	// IssueCertificate signs a PKCS#10 CSR into an end-entity certificate under a
	// CA and profile using the CA's HSM-held key. Requires the issue capability on
	// the CA's tenant (or a per-CA SIGN_CERTIFICATE grant).
	//
	// Errors: PERMISSION_DENIED (no issue capability), INVALID_ARGUMENT (missing
	// or malformed CSR / bad profile), NOT_FOUND (unknown CA), INTERNAL (signing
	// failure).
	IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	// PreviewCertificate validates a would-be issuance through the full fail-closed
	// pre-issuance gate stack (certlint, CAA, name constraints, certificate policy,
	// S/MIME policy, validity caps, attestation posture, and the manual-approval
	// would-park signal) WITHOUT calling the HSM to sign, allocating a durable
	// serial, persisting anything, appending an audit event, or taking a rate-limit
	// slot. It returns the resolved leaf extensions plus each gate's verdict so an
	// operator or CI can validate a request before a real, HSM-consuming issuance.
	// Requires the same issue capability as IssueCertificate.
	PreviewCertificate(ctx context.Context, in *PreviewCertificateRequest, opts ...grpc.CallOption) (*PreviewCertificateResponse, error)
	// ValidateChain builds and validates a supplied leaf certificate (and optional
	// intermediates) against a CA's configured trust anchors and returns a
	// structured verdict: whether a path was built (with the resolved chain), the
	// validity window, per-certificate live revocation status (CRL + OCSP store,
	// including the reversible on-hold state), name-constraint and certificate-
	// policy conformance, weak-key/weak-signature flags, and an overall pass/fail
	// with human-readable reasons. It is a pure read: no HSM is touched, nothing is
	// signed, no serial is allocated, and no audit event is recorded. Requires the
	// same tenant-scoped read standing as GetCertificate on the CA.
	//
	// Errors: PERMISSION_DENIED (no read role), NOT_FOUND (unknown CA / not a
	// tenant member), INVALID_ARGUMENT (missing or malformed certificate input).
	ValidateChain(ctx context.Context, in *ValidateChainRequest, opts ...grpc.CallOption) (*ValidateChainResponse, error)
	// RenewCertificate reissues a previously issued certificate with a fresh
	// serial and validity window, optionally rekeying from a supplied CSR.
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	// RevokeCertificate records a revocation for a serial and invalidates any
	// cached OCSP "good" response so the new status is served immediately.
	RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error)
	// SuspendCertificate places a certificate on hold (RFC 5280 certificateHold) —
	// a reversible revocation. While held the serial is reported revoked by OCSP
	// and listed on the base CRL. Requires the same issue capability as revocation.
	//
	// Errors: PERMISSION_DENIED, INVALID_ARGUMENT (bad serial / already permanently
	// revoked), NOT_FOUND (unknown CA).
	SuspendCertificate(ctx context.Context, in *SuspendCertificateRequest, opts ...grpc.CallOption) (*SuspendCertificateResponse, error)
	// ReleaseCertificate removes a certificate hold, returning the certificate to
	// service: OCSP reports it good, the next base CRL omits it, and the next delta
	// CRL carries removeFromCRL. It succeeds only for a certificate on hold; a
	// permanent revocation cannot be released.
	//
	// Errors: PERMISSION_DENIED, FAILED_PRECONDITION (not on hold / not revoked),
	// NOT_FOUND (unknown CA).
	ReleaseCertificate(ctx context.Context, in *ReleaseCertificateRequest, opts ...grpc.CallOption) (*ReleaseCertificateResponse, error)
	// GetCertificate returns the authority's stored copy of a certificate it
	// issued, including its current status. Requires read standing in the CA's
	// tenant.
	GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error)
	// GetCertificateStatus returns only the lightweight status (valid / expired /
	// revoked / unknown) for a serial.
	GetCertificateStatus(ctx context.Context, in *GetCertificateStatusRequest, opts ...grpc.CallOption) (*GetCertificateStatusResponse, error)
	// ListCertificates lists the certificates a CA has issued.
	ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error)
	// GetCRLMetadata returns distribution metadata for a CA's CRL (number, this/
	// next update, and the public base/delta URLs). It regenerates the CRL on the
	// HSM only when the published copy is stale.
	GetCRLMetadata(ctx context.Context, in *GetCRLMetadataRequest, opts ...grpc.CallOption) (*GetCRLMetadataResponse, error)
	// GetOCSPMetadata returns the OCSP responder endpoint(s) for a CA plus the
	// responder-hardening options in effect (nonce echoing, delegated signer).
	GetOCSPMetadata(ctx context.Context, in *GetOCSPMetadataRequest, opts ...grpc.CallOption) (*GetOCSPMetadataResponse, error)
	// StreamEvents subscribes to the live tamper-evident audit/lifecycle event
	// feed as a server stream — the gRPC peer of the REST Server-Sent-Events
	// endpoint (GET /api/events/stream). Every hash-chained event appended anywhere
	// in the system (HTTP/gRPC handlers, background jobs, protocol servers) is fanned
	// out in real time from the same in-process publisher, so both surfaces observe
	// an identical stream.
	//
	// Authorization and tenant scoping match the SSE feed exactly: audit:read is
	// required, a platform operator sees every tenant (optionally narrowed with the
	// request's tenant selector), and a tenant-scoped principal is confined to its
	// own tenant's events. An optional action narrows the stream to a single audit
	// action.
	//
	// resume_from_seq, when > 0, first replays the durable event log for matching
	// events with a sequence number greater than it (from the persisted event_log
	// cursor) before switching to the live tail, de-duplicating any overlap by
	// sequence number — so a client that records the last seq it saw can reconnect
	// without a gap. Periodic heartbeat messages keep idle streams and any
	// intermediary from idling out and let a client detect a half-open connection.
	//
	// The feed favors liveness over completeness: a subscriber that cannot keep up
	// is told (via a lag message) that its oldest undelivered events were dropped
	// rather than ever blocking the audit-append hot path.
	//
	// Errors: PERMISSION_DENIED (no audit:read role / not a member of the requested
	// tenant), INVALID_ARGUMENT (a multi-tenant principal that did not name a
	// tenant), INTERNAL (event-log replay failure).
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error)
}

type pKIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPKIServiceClient(cc grpc.ClientConnInterface) PKIServiceClient {
	return &pKIServiceClient{cc}
}

func (c *pKIServiceClient) IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_IssueCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) PreviewCertificate(ctx context.Context, in *PreviewCertificateRequest, opts ...grpc.CallOption) (*PreviewCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewCertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_PreviewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) ValidateChain(ctx context.Context, in *ValidateChainRequest, opts ...grpc.CallOption) (*ValidateChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateChainResponse)
	err := c.cc.Invoke(ctx, PKIService_ValidateChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_RevokeCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) SuspendCertificate(ctx context.Context, in *SuspendCertificateRequest, opts ...grpc.CallOption) (*SuspendCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendCertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_SuspendCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) ReleaseCertificate(ctx context.Context, in *ReleaseCertificateRequest, opts ...grpc.CallOption) (*ReleaseCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseCertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_ReleaseCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_GetCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetCertificateStatus(ctx context.Context, in *GetCertificateStatusRequest, opts ...grpc.CallOption) (*GetCertificateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertificateStatusResponse)
	err := c.cc.Invoke(ctx, PKIService_GetCertificateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCertificatesResponse)
	err := c.cc.Invoke(ctx, PKIService_ListCertificates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetCRLMetadata(ctx context.Context, in *GetCRLMetadataRequest, opts ...grpc.CallOption) (*GetCRLMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCRLMetadataResponse)
	err := c.cc.Invoke(ctx, PKIService_GetCRLMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetOCSPMetadata(ctx context.Context, in *GetOCSPMetadataRequest, opts ...grpc.CallOption) (*GetOCSPMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOCSPMetadataResponse)
	err := c.cc.Invoke(ctx, PKIService_GetOCSPMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PKIService_ServiceDesc.Streams[0], PKIService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, StreamEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PKIService_StreamEventsClient = grpc.ServerStreamingClient[StreamEventsResponse]

// PKIServiceServer is the server API for PKIService service.
// All implementations must embed UnimplementedPKIServiceServer
// for forward compatibility.
//
// PKIService is the certificate-lifecycle gRPC surface. Every RPC authorizes the
// caller against the acting CA's tenant using the same RBAC checks as REST and
// appends a tamper-evident audit event for state-changing operations.
type PKIServiceServer interface {
	// IssueCertificate signs a PKCS#10 CSR into an end-entity certificate under a
	// CA and profile using the CA's HSM-held key. Requires the issue capability on
	// the CA's tenant (or a per-CA SIGN_CERTIFICATE grant).
	//
	// Errors: PERMISSION_DENIED (no issue capability), INVALID_ARGUMENT (missing
	// or malformed CSR / bad profile), NOT_FOUND (unknown CA), INTERNAL (signing
	// failure).
	IssueCertificate(context.Context, *IssueCertificateRequest) (*CertificateResponse, error)
	// PreviewCertificate validates a would-be issuance through the full fail-closed
	// pre-issuance gate stack (certlint, CAA, name constraints, certificate policy,
	// S/MIME policy, validity caps, attestation posture, and the manual-approval
	// would-park signal) WITHOUT calling the HSM to sign, allocating a durable
	// serial, persisting anything, appending an audit event, or taking a rate-limit
	// slot. It returns the resolved leaf extensions plus each gate's verdict so an
	// operator or CI can validate a request before a real, HSM-consuming issuance.
	// Requires the same issue capability as IssueCertificate.
	PreviewCertificate(context.Context, *PreviewCertificateRequest) (*PreviewCertificateResponse, error)
	// ValidateChain builds and validates a supplied leaf certificate (and optional
	// intermediates) against a CA's configured trust anchors and returns a
	// structured verdict: whether a path was built (with the resolved chain), the
	// validity window, per-certificate live revocation status (CRL + OCSP store,
	// including the reversible on-hold state), name-constraint and certificate-
	// policy conformance, weak-key/weak-signature flags, and an overall pass/fail
	// with human-readable reasons. It is a pure read: no HSM is touched, nothing is
	// signed, no serial is allocated, and no audit event is recorded. Requires the
	// same tenant-scoped read standing as GetCertificate on the CA.
	//
	// Errors: PERMISSION_DENIED (no read role), NOT_FOUND (unknown CA / not a
	// tenant member), INVALID_ARGUMENT (missing or malformed certificate input).
	ValidateChain(context.Context, *ValidateChainRequest) (*ValidateChainResponse, error)
	// RenewCertificate reissues a previously issued certificate with a fresh
	// serial and validity window, optionally rekeying from a supplied CSR.
	RenewCertificate(context.Context, *RenewCertificateRequest) (*CertificateResponse, error)
	// RevokeCertificate records a revocation for a serial and invalidates any
	// cached OCSP "good" response so the new status is served immediately.
	RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error)
	// SuspendCertificate places a certificate on hold (RFC 5280 certificateHold) —
	// a reversible revocation. While held the serial is reported revoked by OCSP
	// and listed on the base CRL. Requires the same issue capability as revocation.
	//
	// Errors: PERMISSION_DENIED, INVALID_ARGUMENT (bad serial / already permanently
	// revoked), NOT_FOUND (unknown CA).
	SuspendCertificate(context.Context, *SuspendCertificateRequest) (*SuspendCertificateResponse, error)
	// ReleaseCertificate removes a certificate hold, returning the certificate to
	// service: OCSP reports it good, the next base CRL omits it, and the next delta
	// CRL carries removeFromCRL. It succeeds only for a certificate on hold; a
	// permanent revocation cannot be released.
	//
	// Errors: PERMISSION_DENIED, FAILED_PRECONDITION (not on hold / not revoked),
	// NOT_FOUND (unknown CA).
	ReleaseCertificate(context.Context, *ReleaseCertificateRequest) (*ReleaseCertificateResponse, error)
	// GetCertificate returns the authority's stored copy of a certificate it
	// issued, including its current status. Requires read standing in the CA's
	// tenant.
	GetCertificate(context.Context, *GetCertificateRequest) (*GetCertificateResponse, error)
	// GetCertificateStatus returns only the lightweight status (valid / expired /
	// revoked / unknown) for a serial.
	GetCertificateStatus(context.Context, *GetCertificateStatusRequest) (*GetCertificateStatusResponse, error)
	// ListCertificates lists the certificates a CA has issued.
	ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error)
	// GetCRLMetadata returns distribution metadata for a CA's CRL (number, this/
	// next update, and the public base/delta URLs). It regenerates the CRL on the
	// HSM only when the published copy is stale.
	GetCRLMetadata(context.Context, *GetCRLMetadataRequest) (*GetCRLMetadataResponse, error)
	// GetOCSPMetadata returns the OCSP responder endpoint(s) for a CA plus the
	// responder-hardening options in effect (nonce echoing, delegated signer).
	GetOCSPMetadata(context.Context, *GetOCSPMetadataRequest) (*GetOCSPMetadataResponse, error)
	// StreamEvents subscribes to the live tamper-evident audit/lifecycle event
	// feed as a server stream — the gRPC peer of the REST Server-Sent-Events
	// endpoint (GET /api/events/stream). Every hash-chained event appended anywhere
	// in the system (HTTP/gRPC handlers, background jobs, protocol servers) is fanned
	// out in real time from the same in-process publisher, so both surfaces observe
	// an identical stream.
	//
	// Authorization and tenant scoping match the SSE feed exactly: audit:read is
	// required, a platform operator sees every tenant (optionally narrowed with the
	// request's tenant selector), and a tenant-scoped principal is confined to its
	// own tenant's events. An optional action narrows the stream to a single audit
	// action.
	//
	// resume_from_seq, when > 0, first replays the durable event log for matching
	// events with a sequence number greater than it (from the persisted event_log
	// cursor) before switching to the live tail, de-duplicating any overlap by
	// sequence number — so a client that records the last seq it saw can reconnect
	// without a gap. Periodic heartbeat messages keep idle streams and any
	// intermediary from idling out and let a client detect a half-open connection.
	//
	// The feed favors liveness over completeness: a subscriber that cannot keep up
	// is told (via a lag message) that its oldest undelivered events were dropped
	// rather than ever blocking the audit-append hot path.
	//
	// Errors: PERMISSION_DENIED (no audit:read role / not a member of the requested
	// tenant), INVALID_ARGUMENT (a multi-tenant principal that did not name a
	// tenant), INTERNAL (event-log replay failure).
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error
	mustEmbedUnimplementedPKIServiceServer()
}

// UnimplementedPKIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPKIServiceServer struct{}

func (UnimplementedPKIServiceServer) IssueCertificate(context.Context, *IssueCertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueCertificate not implemented")
}
func (UnimplementedPKIServiceServer) PreviewCertificate(context.Context, *PreviewCertificateRequest) (*PreviewCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewCertificate not implemented")
}
func (UnimplementedPKIServiceServer) ValidateChain(context.Context, *ValidateChainRequest) (*ValidateChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateChain not implemented")
}
func (UnimplementedPKIServiceServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedPKIServiceServer) RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeCertificate not implemented")
}
func (UnimplementedPKIServiceServer) SuspendCertificate(context.Context, *SuspendCertificateRequest) (*SuspendCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendCertificate not implemented")
}
func (UnimplementedPKIServiceServer) ReleaseCertificate(context.Context, *ReleaseCertificateRequest) (*ReleaseCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseCertificate not implemented")
}
func (UnimplementedPKIServiceServer) GetCertificate(context.Context, *GetCertificateRequest) (*GetCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedPKIServiceServer) GetCertificateStatus(context.Context, *GetCertificateStatusRequest) (*GetCertificateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificateStatus not implemented")
}
func (UnimplementedPKIServiceServer) ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCertificates not implemented")
}
func (UnimplementedPKIServiceServer) GetCRLMetadata(context.Context, *GetCRLMetadataRequest) (*GetCRLMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCRLMetadata not implemented")
}
func (UnimplementedPKIServiceServer) GetOCSPMetadata(context.Context, *GetOCSPMetadataRequest) (*GetOCSPMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOCSPMetadata not implemented")
}
func (UnimplementedPKIServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedPKIServiceServer) mustEmbedUnimplementedPKIServiceServer() {}
func (UnimplementedPKIServiceServer) testEmbeddedByValue()                    {}

// UnsafePKIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PKIServiceServer will
// result in compilation errors.
type UnsafePKIServiceServer interface {
	mustEmbedUnimplementedPKIServiceServer()
}

func RegisterPKIServiceServer(s grpc.ServiceRegistrar, srv PKIServiceServer) {
	// If the following call pancis, it indicates UnimplementedPKIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PKIService_ServiceDesc, srv)
}

func _PKIService_IssueCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).IssueCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_IssueCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).IssueCertificate(ctx, req.(*IssueCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_PreviewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).PreviewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_PreviewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).PreviewCertificate(ctx, req.(*PreviewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_ValidateChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).ValidateChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_ValidateChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).ValidateChain(ctx, req.(*ValidateChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_RevokeCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).RevokeCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_RevokeCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).RevokeCertificate(ctx, req.(*RevokeCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_SuspendCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).SuspendCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_SuspendCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).SuspendCertificate(ctx, req.(*SuspendCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_ReleaseCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).ReleaseCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_ReleaseCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).ReleaseCertificate(ctx, req.(*ReleaseCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetCertificate(ctx, req.(*GetCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetCertificateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetCertificateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetCertificateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetCertificateStatus(ctx, req.(*GetCertificateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_ListCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).ListCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_ListCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).ListCertificates(ctx, req.(*ListCertificatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetCRLMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCRLMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetCRLMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetCRLMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetCRLMetadata(ctx, req.(*GetCRLMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetOCSPMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOCSPMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetOCSPMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetOCSPMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetOCSPMetadata(ctx, req.(*GetOCSPMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PKIServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, StreamEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PKIService_StreamEventsServer = grpc.ServerStreamingServer[StreamEventsResponse]

// PKIService_ServiceDesc is the grpc.ServiceDesc for PKIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PKIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secsy.pki.v1.PKIService",
	HandlerType: (*PKIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCertificate",
			Handler:    _PKIService_IssueCertificate_Handler,
		},
		{
			MethodName: "PreviewCertificate",
			Handler:    _PKIService_PreviewCertificate_Handler,
		},
		{
			MethodName: "ValidateChain",
			Handler:    _PKIService_ValidateChain_Handler,
		},
		{
			MethodName: "RenewCertificate",
			Handler:    _PKIService_RenewCertificate_Handler,
		},
		{
			MethodName: "RevokeCertificate",
			Handler:    _PKIService_RevokeCertificate_Handler,
		},
		{
			MethodName: "SuspendCertificate",
			Handler:    _PKIService_SuspendCertificate_Handler,
		},
		{
			MethodName: "ReleaseCertificate",
			Handler:    _PKIService_ReleaseCertificate_Handler,
		},
		{
			MethodName: "GetCertificate",
			Handler:    _PKIService_GetCertificate_Handler,
		},
		{
			MethodName: "GetCertificateStatus",
			Handler:    _PKIService_GetCertificateStatus_Handler,
		},
		{
			MethodName: "ListCertificates",
			Handler:    _PKIService_ListCertificates_Handler,
		},
		{
			MethodName: "GetCRLMetadata",
			Handler:    _PKIService_GetCRLMetadata_Handler,
		},
		{
			MethodName: "GetOCSPMetadata",
			Handler:    _PKIService_GetOCSPMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _PKIService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pki/v1/pki.proto",
}
