// secsy-pki gRPC API surface (Task 56).
//
// This service exposes the core PKI operations — issue, renew, revoke, and
// status/metadata lookups — alongside the existing REST API. It is a thin
// transport over the same ca.Manager / RBAC / audit / rate-limit / tracing
// plumbing that backs REST, so both protocols enforce identical authorization,
// tenant scoping, and audit semantics.
//
// Authentication mirrors REST: an `authorization` request-metadata header
// (Basic root credentials or a Bearer OIDC token) and/or a mutual-TLS client
// certificate bound to an operator principal. Errors map to canonical gRPC
// status codes (see the service comments). Request IDs and W3C trace context
// propagate through call metadata.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pki/v1/pki.proto

package pkiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PKIService_IssueCertificate_FullMethodName     = "/secsy.pki.v1.PKIService/IssueCertificate"
	PKIService_RenewCertificate_FullMethodName     = "/secsy.pki.v1.PKIService/RenewCertificate"
	PKIService_RevokeCertificate_FullMethodName    = "/secsy.pki.v1.PKIService/RevokeCertificate"
	PKIService_GetCertificate_FullMethodName       = "/secsy.pki.v1.PKIService/GetCertificate"
	PKIService_GetCertificateStatus_FullMethodName = "/secsy.pki.v1.PKIService/GetCertificateStatus"
	PKIService_ListCertificates_FullMethodName     = "/secsy.pki.v1.PKIService/ListCertificates"
	PKIService_GetCRLMetadata_FullMethodName       = "/secsy.pki.v1.PKIService/GetCRLMetadata"
	PKIService_GetOCSPMetadata_FullMethodName      = "/secsy.pki.v1.PKIService/GetOCSPMetadata"
)

// PKIServiceClient is the client API for PKIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PKIService is the certificate-lifecycle gRPC surface. Every RPC authorizes the
// caller against the acting CA's tenant using the same RBAC checks as REST and
// appends a tamper-evident audit event for state-changing operations.
type PKIServiceClient interface {
	// IssueCertificate signs a PKCS#10 CSR into an end-entity certificate under a
	// CA and profile using the CA's HSM-held key. Requires the issue capability on
	// the CA's tenant (or a per-CA SIGN_CERTIFICATE grant).
	//
	// Errors: PERMISSION_DENIED (no issue capability), INVALID_ARGUMENT (missing
	// or malformed CSR / bad profile), NOT_FOUND (unknown CA), INTERNAL (signing
	// failure).
	IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	// RenewCertificate reissues a previously issued certificate with a fresh
	// serial and validity window, optionally rekeying from a supplied CSR.
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	// RevokeCertificate records a revocation for a serial and invalidates any
	// cached OCSP "good" response so the new status is served immediately.
	RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error)
	// GetCertificate returns the authority's stored copy of a certificate it
	// issued, including its current status. Requires read standing in the CA's
	// tenant.
	GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error)
	// GetCertificateStatus returns only the lightweight status (valid / expired /
	// revoked / unknown) for a serial.
	GetCertificateStatus(ctx context.Context, in *GetCertificateStatusRequest, opts ...grpc.CallOption) (*GetCertificateStatusResponse, error)
	// ListCertificates lists the certificates a CA has issued.
	ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error)
	// GetCRLMetadata returns distribution metadata for a CA's CRL (number, this/
	// next update, and the public base/delta URLs). It regenerates the CRL on the
	// HSM only when the published copy is stale.
	GetCRLMetadata(ctx context.Context, in *GetCRLMetadataRequest, opts ...grpc.CallOption) (*GetCRLMetadataResponse, error)
	// GetOCSPMetadata returns the OCSP responder endpoint(s) for a CA plus the
	// responder-hardening options in effect (nonce echoing, delegated signer).
	GetOCSPMetadata(ctx context.Context, in *GetOCSPMetadataRequest, opts ...grpc.CallOption) (*GetOCSPMetadataResponse, error)
}

type pKIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPKIServiceClient(cc grpc.ClientConnInterface) PKIServiceClient {
	return &pKIServiceClient{cc}
}

func (c *pKIServiceClient) IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_IssueCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_RevokeCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertificateResponse)
	err := c.cc.Invoke(ctx, PKIService_GetCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetCertificateStatus(ctx context.Context, in *GetCertificateStatusRequest, opts ...grpc.CallOption) (*GetCertificateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertificateStatusResponse)
	err := c.cc.Invoke(ctx, PKIService_GetCertificateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCertificatesResponse)
	err := c.cc.Invoke(ctx, PKIService_ListCertificates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetCRLMetadata(ctx context.Context, in *GetCRLMetadataRequest, opts ...grpc.CallOption) (*GetCRLMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCRLMetadataResponse)
	err := c.cc.Invoke(ctx, PKIService_GetCRLMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetOCSPMetadata(ctx context.Context, in *GetOCSPMetadataRequest, opts ...grpc.CallOption) (*GetOCSPMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOCSPMetadataResponse)
	err := c.cc.Invoke(ctx, PKIService_GetOCSPMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PKIServiceServer is the server API for PKIService service.
// All implementations must embed UnimplementedPKIServiceServer
// for forward compatibility.
//
// PKIService is the certificate-lifecycle gRPC surface. Every RPC authorizes the
// caller against the acting CA's tenant using the same RBAC checks as REST and
// appends a tamper-evident audit event for state-changing operations.
type PKIServiceServer interface {
	// IssueCertificate signs a PKCS#10 CSR into an end-entity certificate under a
	// CA and profile using the CA's HSM-held key. Requires the issue capability on
	// the CA's tenant (or a per-CA SIGN_CERTIFICATE grant).
	//
	// Errors: PERMISSION_DENIED (no issue capability), INVALID_ARGUMENT (missing
	// or malformed CSR / bad profile), NOT_FOUND (unknown CA), INTERNAL (signing
	// failure).
	IssueCertificate(context.Context, *IssueCertificateRequest) (*CertificateResponse, error)
	// RenewCertificate reissues a previously issued certificate with a fresh
	// serial and validity window, optionally rekeying from a supplied CSR.
	RenewCertificate(context.Context, *RenewCertificateRequest) (*CertificateResponse, error)
	// RevokeCertificate records a revocation for a serial and invalidates any
	// cached OCSP "good" response so the new status is served immediately.
	RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error)
	// GetCertificate returns the authority's stored copy of a certificate it
	// issued, including its current status. Requires read standing in the CA's
	// tenant.
	GetCertificate(context.Context, *GetCertificateRequest) (*GetCertificateResponse, error)
	// GetCertificateStatus returns only the lightweight status (valid / expired /
	// revoked / unknown) for a serial.
	GetCertificateStatus(context.Context, *GetCertificateStatusRequest) (*GetCertificateStatusResponse, error)
	// ListCertificates lists the certificates a CA has issued.
	ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error)
	// GetCRLMetadata returns distribution metadata for a CA's CRL (number, this/
	// next update, and the public base/delta URLs). It regenerates the CRL on the
	// HSM only when the published copy is stale.
	GetCRLMetadata(context.Context, *GetCRLMetadataRequest) (*GetCRLMetadataResponse, error)
	// GetOCSPMetadata returns the OCSP responder endpoint(s) for a CA plus the
	// responder-hardening options in effect (nonce echoing, delegated signer).
	GetOCSPMetadata(context.Context, *GetOCSPMetadataRequest) (*GetOCSPMetadataResponse, error)
	mustEmbedUnimplementedPKIServiceServer()
}

// UnimplementedPKIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPKIServiceServer struct{}

func (UnimplementedPKIServiceServer) IssueCertificate(context.Context, *IssueCertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueCertificate not implemented")
}
func (UnimplementedPKIServiceServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedPKIServiceServer) RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeCertificate not implemented")
}
func (UnimplementedPKIServiceServer) GetCertificate(context.Context, *GetCertificateRequest) (*GetCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedPKIServiceServer) GetCertificateStatus(context.Context, *GetCertificateStatusRequest) (*GetCertificateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificateStatus not implemented")
}
func (UnimplementedPKIServiceServer) ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCertificates not implemented")
}
func (UnimplementedPKIServiceServer) GetCRLMetadata(context.Context, *GetCRLMetadataRequest) (*GetCRLMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCRLMetadata not implemented")
}
func (UnimplementedPKIServiceServer) GetOCSPMetadata(context.Context, *GetOCSPMetadataRequest) (*GetOCSPMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOCSPMetadata not implemented")
}
func (UnimplementedPKIServiceServer) mustEmbedUnimplementedPKIServiceServer() {}
func (UnimplementedPKIServiceServer) testEmbeddedByValue()                    {}

// UnsafePKIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PKIServiceServer will
// result in compilation errors.
type UnsafePKIServiceServer interface {
	mustEmbedUnimplementedPKIServiceServer()
}

func RegisterPKIServiceServer(s grpc.ServiceRegistrar, srv PKIServiceServer) {
	// If the following call pancis, it indicates UnimplementedPKIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PKIService_ServiceDesc, srv)
}

func _PKIService_IssueCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).IssueCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_IssueCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).IssueCertificate(ctx, req.(*IssueCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_RevokeCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).RevokeCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_RevokeCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).RevokeCertificate(ctx, req.(*RevokeCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetCertificate(ctx, req.(*GetCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetCertificateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetCertificateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetCertificateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetCertificateStatus(ctx, req.(*GetCertificateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_ListCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).ListCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_ListCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).ListCertificates(ctx, req.(*ListCertificatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetCRLMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCRLMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetCRLMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetCRLMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetCRLMetadata(ctx, req.(*GetCRLMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetOCSPMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOCSPMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetOCSPMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetOCSPMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetOCSPMetadata(ctx, req.(*GetOCSPMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PKIService_ServiceDesc is the grpc.ServiceDesc for PKIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PKIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secsy.pki.v1.PKIService",
	HandlerType: (*PKIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCertificate",
			Handler:    _PKIService_IssueCertificate_Handler,
		},
		{
			MethodName: "RenewCertificate",
			Handler:    _PKIService_RenewCertificate_Handler,
		},
		{
			MethodName: "RevokeCertificate",
			Handler:    _PKIService_RevokeCertificate_Handler,
		},
		{
			MethodName: "GetCertificate",
			Handler:    _PKIService_GetCertificate_Handler,
		},
		{
			MethodName: "GetCertificateStatus",
			Handler:    _PKIService_GetCertificateStatus_Handler,
		},
		{
			MethodName: "ListCertificates",
			Handler:    _PKIService_ListCertificates_Handler,
		},
		{
			MethodName: "GetCRLMetadata",
			Handler:    _PKIService_GetCRLMetadata_Handler,
		},
		{
			MethodName: "GetOCSPMetadata",
			Handler:    _PKIService_GetOCSPMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pki/v1/pki.proto",
}
