#!/usr/bin/env bash
#
# setup-softhsm.sh — Initialize a SoftHSM2 token for secsy-pki development & CI.
#
# This script is idempotent: re-running it will not create duplicate tokens.
# If a token with the configured label already exists it is reused (unless
# SOFTHSM_REINIT=1 is set, in which case the token directory is wiped first).
#
# It writes a SoftHSM2 configuration file, initializes a token with a known
# label / SO PIN / user PIN, and prints the PKCS#11 module path plus the
# environment variables needed by the secsy-pki server and pkcs11-tool.
#
# Usage:
#   ./scripts/setup-softhsm.sh                # use defaults
#   SOFTHSM_TOKEN_LABEL=my-token ./scripts/setup-softhsm.sh
#   SOFTHSM_REINIT=1 ./scripts/setup-softhsm.sh   # wipe & recreate the token
#
# To load the exported environment into your current shell:
#   eval "$(./scripts/setup-softhsm.sh --export-env)"
#
set -euo pipefail

# ----------------------------------------------------------------------------
# Configuration (override via environment variables)
# ----------------------------------------------------------------------------
SOFTHSM_TOKEN_LABEL="${SOFTHSM_TOKEN_LABEL:-secsy-pki-root}"
SOFTHSM_SO_PIN="${SOFTHSM_SO_PIN:-5678}"
SOFTHSM_USER_PIN="${SOFTHSM_USER_PIN:-1234}"
SOFTHSM_TOKEN_DIR="${SOFTHSM_TOKEN_DIR:-/tmp/softhsm/tokens}"
SOFTHSM_CONF="${SOFTHSM2_CONF:-/tmp/softhsm2.conf}"
SOFTHSM_REINIT="${SOFTHSM_REINIT:-0}"

# Locate the SoftHSM2 PKCS#11 module. The path differs across distributions,
# so probe the common locations rather than hard-coding one.
find_module() {
    local candidates=(
        "/usr/lib/softhsm/libsofthsm2.so"
        "/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so"
        "/usr/lib64/pkcs11/libsofthsm2.so"
        "/usr/lib/pkcs11/libsofthsm2.so"
        "/usr/local/lib/softhsm/libsofthsm2.so"
        "/opt/homebrew/lib/softhsm/libsofthsm2.so"
    )
    for c in "${candidates[@]}"; do
        if [[ -f "$c" ]]; then
            echo "$c"
            return 0
        fi
    done
    return 1
}

# ----------------------------------------------------------------------------
# --export-env: emit shell-eval'able exports and exit (no side effects).
# ----------------------------------------------------------------------------
if [[ "${1:-}" == "--export-env" ]]; then
    module_path="$(find_module || true)"
    printf 'export SOFTHSM2_CONF=%q\n' "$SOFTHSM_CONF"
    printf 'export SECSY_PKCS11_MODULE=%q\n' "$module_path"
    printf 'export SECSY_TOKEN_LABEL=%q\n' "$SOFTHSM_TOKEN_LABEL"
    printf 'export SECSY_USER_PIN=%q\n' "$SOFTHSM_USER_PIN"
    printf 'export SECSY_SO_PIN=%q\n' "$SOFTHSM_SO_PIN"
    exit 0
fi

log() { echo "==> $*"; }
err() { echo "ERROR: $*" >&2; }

# ----------------------------------------------------------------------------
# Preflight checks
# ----------------------------------------------------------------------------
if ! command -v softhsm2-util >/dev/null 2>&1; then
    err "softhsm2-util not found. Install it first:"
    err "  Debian/Ubuntu: sudo apt-get install -y softhsm2 opensc"
    err "  RHEL/Fedora:   sudo dnf install -y softhsm opensc"
    err "  macOS:         brew install softhsm opensc"
    exit 1
fi

if ! command -v pkcs11-tool >/dev/null 2>&1; then
    err "pkcs11-tool not found. Install the 'opensc' package (see above)."
    exit 1
fi

MODULE_PATH="$(find_module || true)"
if [[ -z "$MODULE_PATH" ]]; then
    err "Could not locate libsofthsm2.so in any known location."
    err "Set SOFTHSM2_CONF and place the module, or export the path manually."
    exit 1
fi

# ----------------------------------------------------------------------------
# Write SoftHSM2 configuration
# ----------------------------------------------------------------------------
export SOFTHSM2_CONF="$SOFTHSM_CONF"

log "Using SoftHSM2 module: $MODULE_PATH"
log "Token directory:       $SOFTHSM_TOKEN_DIR"
log "SoftHSM2 config:        $SOFTHSM_CONF"

if [[ "$SOFTHSM_REINIT" == "1" ]]; then
    log "SOFTHSM_REINIT=1 — wiping token directory."
    rm -rf "${SOFTHSM_TOKEN_DIR:?}"
fi

mkdir -p "$SOFTHSM_TOKEN_DIR"
cat > "$SOFTHSM_CONF" <<EOF
# Generated by scripts/setup-softhsm.sh — do not edit by hand.
directories.tokendir = $SOFTHSM_TOKEN_DIR
objectstore.backend = file
log.level = INFO
slots.removable = false
EOF

# ----------------------------------------------------------------------------
# Initialize the token (idempotent)
# ----------------------------------------------------------------------------
if softhsm2-util --show-slots 2>/dev/null | grep -qF "Label:            $SOFTHSM_TOKEN_LABEL" \
    || softhsm2-util --show-slots 2>/dev/null | grep -qF "$SOFTHSM_TOKEN_LABEL"; then
    log "Token '$SOFTHSM_TOKEN_LABEL' already exists — reusing it."
    log "(Set SOFTHSM_REINIT=1 to recreate it from scratch.)"
else
    log "Initializing token '$SOFTHSM_TOKEN_LABEL'..."
    softhsm2-util --init-token --free \
        --label "$SOFTHSM_TOKEN_LABEL" \
        --pin "$SOFTHSM_USER_PIN" \
        --so-pin "$SOFTHSM_SO_PIN"
    log "Token initialized."
fi

# ----------------------------------------------------------------------------
# Verify token creation
# ----------------------------------------------------------------------------
log "Verifying token via pkcs11-tool --list-slots..."
pkcs11-tool --module "$MODULE_PATH" --list-slots

# ----------------------------------------------------------------------------
# Summary / exported values
# ----------------------------------------------------------------------------
cat <<EOF

============================================================
 SoftHSM token ready.
============================================================
 PKCS#11 module : $MODULE_PATH
 Token label    : $SOFTHSM_TOKEN_LABEL
 User PIN       : $SOFTHSM_USER_PIN
 SO PIN         : $SOFTHSM_SO_PIN
 SOFTHSM2_CONF  : $SOFTHSM_CONF
 Token dir      : $SOFTHSM_TOKEN_DIR

 Load these into your shell with:
   eval "\$($0 --export-env)"

 Or export manually:
   export SOFTHSM2_CONF=$SOFTHSM_CONF
   export SECSY_PKCS11_MODULE=$MODULE_PATH
============================================================
EOF
