// Package est implements the EST (Enrollment over Secure Transport, RFC 7030)
// server operations on top of the HSM-backed ca.Manager issuance layer:
//
//   - GET  /.well-known/est/cacerts       — CA certificate distribution
//   - POST /.well-known/est/simpleenroll  — initial enrollment
//   - POST /.well-known/est/simplereenroll — renewal
//   - POST /.well-known/est/serverkeygen  — server-side key generation (optional)
//
// Clients authenticate with HTTP Basic credentials (operator-provisioned, the
// EST analogue of an RBAC grant) or a TLS client certificate previously issued
// by this CA. Every leaf is signed through the shared ca.Manager, so the CA key
// never leaves its provider.
package est

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/subtle"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"log"
	"math"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/blechschmidt/secsy-pki/server/internal/attestation"
	"github.com/blechschmidt/secsy-pki/server/internal/audit"
	"github.com/blechschmidt/secsy-pki/server/internal/ca"
	"github.com/blechschmidt/secsy-pki/server/internal/cms"
	"github.com/blechschmidt/secsy-pki/server/internal/database"
	"github.com/blechschmidt/secsy-pki/server/internal/keyprovider"
	"github.com/blechschmidt/secsy-pki/server/internal/metrics"
	"github.com/blechschmidt/secsy-pki/server/internal/models"
	"github.com/blechschmidt/secsy-pki/server/internal/pki"
)

// User is an operator-provisioned EST Basic-auth credential. Password is the
// shared secret; Profile constrains what the credential may enroll.
type User struct {
	Password string
	Profile  string
}

// Config configures the EST server.
type Config struct {
	// BasePath is the URL prefix (default "/.well-known/est"). RFC 7030 also
	// allows an arbitrary additional path segment for CA labeling, which callers
	// may include here.
	BasePath string
	// CAID is the issuing CA. Unlike SCEP, EST places no RSA requirement on it.
	CAID string
	// Profile is the default certificate profile (default "client").
	Profile string
	// Users maps a Basic-auth username to its credential + profile.
	Users map[string]User
	// AllowTLSClientReenroll permits simplereenroll (and simpleenroll) to be
	// authorized by a TLS client certificate this CA previously issued, without
	// Basic credentials (RFC 7030 §3.3.2 certificate-based client auth).
	AllowTLSClientReenroll bool
	// EnableServerKeygen enables the /serverkeygen endpoint.
	EnableServerKeygen bool
	// ServerKeygenKeyType selects the key type generated by /serverkeygen
	// (keyprovider.KeyType* values; default RSA-2048). The key is generated in
	// memory and returned to the client — it is deliberately NOT an HSM key,
	// since the private key must leave the server.
	ServerKeygenKeyType string
	// Attestation, when set, verifies hardware key-attestation evidence carried in
	// the enrollment CSR before issuance, per the profile's attestation mode
	// (Task 49). A nil verifier disables the gate (attestation off everywhere).
	Attestation *attestation.Verifier
}

func (c Config) withDefaults() Config {
	if c.BasePath == "" {
		c.BasePath = "/.well-known/est"
	}
	c.BasePath = "/" + strings.Trim(c.BasePath, "/")
	if c.Profile == "" {
		c.Profile = "client"
	}
	if c.ServerKeygenKeyType == "" {
		c.ServerKeygenKeyType = keyprovider.KeyTypeRSA2048
	}
	return c
}

// Server implements the EST endpoints.
type Server struct {
	db       *database.DB
	provider keyprovider.Provider
	caMgr    *ca.Manager
	cfg      Config
	now      func() time.Time
}

// New constructs an EST server. Call Register to attach the endpoints.
func New(db *database.DB, provider keyprovider.Provider, cfg Config) *Server {
	return &Server{
		db:       db,
		provider: provider,
		caMgr:    ca.NewManager(db, provider),
		cfg:      cfg.withDefaults(),
		now:      time.Now,
	}
}

// SetClock overrides the time source (used by tests).
func (s *Server) SetClock(now func() time.Time) { s.now = now }

// Register mounts the EST endpoints on mux.
func (s *Server) Register(mux *http.ServeMux) {
	p := s.cfg.BasePath
	mux.HandleFunc("GET "+p+"/cacerts", s.handleCACerts)
	mux.HandleFunc("POST "+p+"/simpleenroll", s.handleEnroll(false))
	mux.HandleFunc("POST "+p+"/simplereenroll", s.handleEnroll(true))
	if s.cfg.EnableServerKeygen {
		mux.HandleFunc("POST "+p+"/serverkeygen", s.handleServerKeygen)
	}
	log.Printf("EST server enabled at %s (CA=%s profile=%s, serverkeygen=%v)", p, s.cfg.CAID, s.cfg.Profile, s.cfg.EnableServerKeygen)
}

// handleCACerts returns the CA chain as a base64 certs-only PKCS#7 (RFC 7030
// §4.1). This endpoint is unauthenticated by design.
func (s *Server) handleCACerts(w http.ResponseWriter, r *http.Request) {
	chain, err := s.caChain()
	if err != nil {
		http.Error(w, "CA unavailable", http.StatusInternalServerError)
		log.Printf("est: cacerts: %v", err)
		return
	}
	p7, err := cms.DegenerateCertsOnly(chain)
	if err != nil {
		http.Error(w, "encoding CA chain", http.StatusInternalServerError)
		return
	}
	s.recordEvent(r, "est:anonymous", audit.ActionESTCACerts, s.cfg.CAID, audit.ResultSuccess, "")
	writePKCS7(w, p7)
}

// handleEnroll services simpleenroll and simplereenroll. Both take a base64
// PKCS#10 and return a base64 certs-only PKCS#7 with the issued certificate.
func (s *Server) handleEnroll(reenroll bool) http.HandlerFunc {
	action := audit.ActionESTEnroll
	if reenroll {
		action = audit.ActionESTReenroll
	}
	return func(w http.ResponseWriter, r *http.Request) {
		profile, actor, ok := s.authenticate(r, reenroll)
		if !ok {
			s.unauthorized(w)
			return
		}
		csr, err := s.readCSR(r)
		if err != nil {
			http.Error(w, "invalid CSR: "+err.Error(), http.StatusBadRequest)
			return
		}
		if !s.enforceAttestation(r, csr, profile, actor) {
			http.Error(w, "hardware key attestation required and missing or invalid", http.StatusForbidden)
			return
		}
		leaf, err := s.issue(r, csr, profile, actor)
		if err != nil {
			s.recordEvent(r, actor, action, csr.Subject.CommonName, audit.ResultError, err.Error())
			writeIssuanceError(w, err)
			log.Printf("est: issuance failed: %v", err)
			return
		}
		p7, err := cms.DegenerateCertsOnly([]*x509.Certificate{leaf})
		if err != nil {
			http.Error(w, "encoding response", http.StatusInternalServerError)
			return
		}
		s.recordEvent(r, actor, action, leaf.Subject.CommonName, audit.ResultSuccess,
			"serial="+leaf.SerialNumber.String()+" profile="+profile)
		writePKCS7(w, p7)
	}
}

// handleServerKeygen generates a key pair server-side, enrolls it, and returns
// the private key (PKCS#8) and the issued certificate (certs-only PKCS#7) in a
// multipart/mixed body (RFC 7030 §4.4). The generated private key is created in
// memory and returned to the client; it is intentionally not HSM-resident.
func (s *Server) handleServerKeygen(w http.ResponseWriter, r *http.Request) {
	profile, actor, ok := s.authenticate(r, false)
	if !ok {
		s.unauthorized(w)
		return
	}
	csr, err := s.readCSR(r)
	if err != nil {
		http.Error(w, "invalid CSR: "+err.Error(), http.StatusBadRequest)
		return
	}
	// A server-generated key is, by construction, not hardware-resident and
	// cannot be attested. If the profile requires attestation, serverkeygen is
	// incompatible and must be refused fail-closed.
	if s.cfg.Attestation.Mode(profile) == attestation.ModeRequire {
		s.recordEvent(r, actor, audit.ActionCertAttestation, csr.Subject.CommonName, audit.ResultDenied,
			"serverkeygen incompatible with required attestation (server-generated key is not hardware-resident)")
		metrics.AttestationDenied.Inc("est")
		metrics.AttestationChecks.Inc("est", string(attestation.ModeRequire), "missing")
		http.Error(w, "profile requires hardware key attestation; server-side key generation is not permitted", http.StatusForbidden)
		return
	}

	priv, pub, err := generateKeyPair(s.cfg.ServerKeygenKeyType)
	if err != nil {
		http.Error(w, "key generation failed", http.StatusInternalServerError)
		return
	}
	// Rebuild the CSR around the server-generated public key, preserving the
	// client's requested subject and SANs.
	newCSR, err := reCSR(csr, priv, pub)
	if err != nil {
		http.Error(w, "rebuilding CSR: "+err.Error(), http.StatusInternalServerError)
		return
	}
	leaf, err := s.issue(r, newCSR, profile, actor)
	if err != nil {
		s.recordEvent(r, actor, audit.ActionESTServerKeyGen, csr.Subject.CommonName, audit.ResultError, err.Error())
		writeIssuanceError(w, err)
		return
	}
	keyDER, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		http.Error(w, "encoding private key", http.StatusInternalServerError)
		return
	}
	p7, err := cms.DegenerateCertsOnly([]*x509.Certificate{leaf})
	if err != nil {
		http.Error(w, "encoding response", http.StatusInternalServerError)
		return
	}
	s.recordEvent(r, actor, audit.ActionESTServerKeyGen, leaf.Subject.CommonName, audit.ResultSuccess,
		"serial="+leaf.SerialNumber.String()+" profile="+profile)
	writeServerKeygen(w, keyDER, p7)
}

// writeIssuanceError maps an issuance failure to EST's HTTP semantics: a
// suspended tenant is 403, tenant quota exhaustion is 429 with a Retry-After
// when the daily window resets, anything else stays an opaque 500.
func writeIssuanceError(w http.ResponseWriter, err error) {
	var susp *models.TenantSuspendedError
	if errors.As(err, &susp) {
		http.Error(w, "tenant is suspended; enrollment is disabled", http.StatusForbidden)
		return
	}
	var quota *models.QuotaExceededError
	if errors.As(err, &quota) {
		if quota.RetryAfter > 0 {
			secs := int(math.Ceil(quota.RetryAfter.Seconds()))
			if secs < 1 {
				secs = 1
			}
			w.Header().Set("Retry-After", strconv.Itoa(secs))
		}
		http.Error(w, "tenant issuance quota exceeded", http.StatusTooManyRequests)
		return
	}
	http.Error(w, "issuance failed", http.StatusInternalServerError)
}

// issue signs a CSR through the shared HSM-backed ca.Manager.
func (s *Server) issue(r *http.Request, csr *x509.CertificateRequest, profile, actor string) (*x509.Certificate, error) {
	csrPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE REQUEST", Bytes: csr.Raw})
	result, err := s.caMgr.IssueCertificate(r.Context(), ca.IssueSpec{
		CAID:        s.cfg.CAID,
		CSRPEM:      csrPEM,
		Profile:     profile,
		RequestedBy: actor,
	})
	if err != nil {
		return nil, err
	}
	return result.Certificate, nil
}

// authenticate authorizes a request via TLS client certificate (when enabled)
// or HTTP Basic credentials, returning the profile and an audit actor label.
func (s *Server) authenticate(r *http.Request, _ bool) (profile, actor string, ok bool) {
	// Certificate-based client authentication: a TLS client certificate this CA
	// issued authorizes (re)enrollment without a shared secret.
	if s.cfg.AllowTLSClientReenroll && r.TLS != nil && len(r.TLS.PeerCertificates) > 0 {
		if cert := s.validClientCert(r.TLS.PeerCertificates[0]); cert != nil {
			return s.cfg.Profile, "est-cert:" + cert.Subject.CommonName, true
		}
	}

	user, pass, hasBasic := r.BasicAuth()
	if hasBasic {
		if cred, found := s.cfg.Users[user]; found &&
			subtle.ConstantTimeCompare([]byte(pass), []byte(cred.Password)) == 1 {
			p := cred.Profile
			if p == "" {
				p = s.cfg.Profile
			}
			return p, "est:" + user, true
		}
	}
	return "", "", false
}

// validClientCert returns the certificate if it is a currently-valid,
// non-revoked certificate issued by this CA.
func (s *Server) validClientCert(cert *x509.Certificate) *x509.Certificate {
	caCert, _, err := s.caCertModel()
	if err != nil {
		return nil
	}
	if cert.CheckSignatureFrom(caCert) != nil {
		return nil
	}
	now := s.now()
	if now.Before(cert.NotBefore) || now.After(cert.NotAfter) {
		return nil
	}
	rec, err := s.db.GetIssuedCertificate(s.cfg.CAID, cert.SerialNumber.String())
	if err != nil || rec == nil || rec.Status != models.CertStatusValid {
		return nil
	}
	return cert
}

func (s *Server) unauthorized(w http.ResponseWriter) {
	w.Header().Set("WWW-Authenticate", `Basic realm="EST"`)
	http.Error(w, "authentication required", http.StatusUnauthorized)
}

// readCSR reads and parses the PKCS#10 from an EST enroll request body. The body
// is base64 per RFC 7030; raw DER is tolerated as a fallback.
func (s *Server) readCSR(r *http.Request) (*x509.CertificateRequest, error) {
	body, err := io.ReadAll(r.Body)
	if err != nil {
		return nil, err
	}
	der := body
	if decoded, derr := base64.StdEncoding.DecodeString(strings.TrimSpace(string(body))); derr == nil {
		der = decoded
	}
	csr, err := x509.ParseCertificateRequest(der)
	if err != nil {
		return nil, err
	}
	if err := csr.CheckSignature(); err != nil {
		return nil, fmt.Errorf("CSR signature invalid: %w", err)
	}
	return csr, nil
}

// ---- CA plumbing ----------------------------------------------------------

func (s *Server) caCertModel() (*x509.Certificate, *models.CA, error) {
	m, err := s.db.GetCA(s.cfg.CAID)
	if err != nil {
		return nil, nil, err
	}
	if m == nil || m.Certificate == "" {
		return nil, nil, fmt.Errorf("EST CA %q not found or has no certificate", s.cfg.CAID)
	}
	cert, err := pki.ParseCertificatePEM([]byte(m.Certificate))
	if err != nil {
		return nil, nil, err
	}
	return cert, m, nil
}

func (s *Server) caChain() ([]*x509.Certificate, error) {
	var chain []*x509.Certificate
	id := s.cfg.CAID
	for id != "" {
		m, err := s.db.GetCA(id)
		if err != nil {
			return nil, err
		}
		if m == nil || m.Certificate == "" {
			break
		}
		cert, err := pki.ParseCertificatePEM([]byte(m.Certificate))
		if err != nil {
			return nil, err
		}
		chain = append(chain, cert)
		if m.ParentID == nil {
			break
		}
		id = *m.ParentID
	}
	if len(chain) == 0 {
		return nil, fmt.Errorf("EST CA %q not found", s.cfg.CAID)
	}
	return chain, nil
}

// enforceAttestation runs the enrollment key-attestation gate against the CSR
// and returns whether issuance may proceed. It records a cert.attestation audit
// event and updates metrics for every outcome (pass, permissive-passthrough, or
// fail-closed denial). A nil verifier is inert (attestation disabled).
func (s *Server) enforceAttestation(r *http.Request, csr *x509.CertificateRequest, profile, actor string) bool {
	dec := s.cfg.Attestation.VerifyEnrollment(profile, csr)
	if dec.Mode == attestation.ModeOff {
		return true
	}

	result := attestationResultLabel(dec)
	metrics.AttestationChecks.Inc("est", string(dec.Mode), result)
	if dec.Result != nil && dec.Result.Verified {
		metrics.AttestationVerified.Inc(dec.Result.Format)
	}

	if !dec.Allow {
		metrics.AttestationDenied.Inc("est")
		s.recordEvent(r, actor, audit.ActionCertAttestation, csr.Subject.CommonName, audit.ResultDenied, dec.Detail)
		return false
	}
	s.recordEvent(r, actor, audit.ActionCertAttestation, csr.Subject.CommonName, audit.ResultSuccess, dec.Detail)
	return true
}

// attestationResultLabel maps an attestation decision to the metric "result"
// label ("pass"|"missing"|"invalid"|"skip"), shared across enrollment paths.
func attestationResultLabel(dec attestation.Decision) string {
	switch {
	case dec.Mode == attestation.ModeOff:
		return "skip"
	case dec.Result != nil && dec.Result.Verified:
		return "pass"
	case dec.Missing:
		return "missing"
	default:
		return "invalid"
	}
}

func (s *Server) recordEvent(r *http.Request, actor, action, target, result, detail string) {
	e := &audit.Event{
		ID:         uuid.New().String(),
		Actor:      actor,
		ActorRoles: "est",
		Action:     action,
		Target:     target,
		Result:     result,
		Detail:     detail,
		IP:         clientIP(r),
	}
	if err := s.db.AppendEvent(e); err != nil {
		log.Printf("est: appending audit event %q: %v", action, err)
	}
}

func clientIP(r *http.Request) string {
	if fwd := r.Header.Get("X-Forwarded-For"); fwd != "" {
		return fwd
	}
	return r.RemoteAddr
}

// ---- key generation for /serverkeygen -------------------------------------

func generateKeyPair(keyType string) (priv crypto.Signer, pub crypto.PublicKey, err error) {
	switch keyType {
	case keyprovider.KeyTypeRSA2048:
		k, e := rsa.GenerateKey(rand.Reader, 2048)
		return k, &k.PublicKey, e
	case keyprovider.KeyTypeRSA4096:
		k, e := rsa.GenerateKey(rand.Reader, 4096)
		return k, &k.PublicKey, e
	case keyprovider.KeyTypeECDSAP256:
		k, e := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		return k, &k.PublicKey, e
	case keyprovider.KeyTypeECDSAP384:
		k, e := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
		return k, &k.PublicKey, e
	default:
		return nil, nil, fmt.Errorf("est: unsupported serverkeygen key type %q", keyType)
	}
}

// reCSR builds a fresh CSR around a server-generated key, copying the requested
// subject and SANs from the client's original CSR.
func reCSR(orig *x509.CertificateRequest, priv crypto.Signer, _ crypto.PublicKey) (*x509.CertificateRequest, error) {
	tmpl := &x509.CertificateRequest{
		Subject:        orig.Subject,
		DNSNames:       orig.DNSNames,
		IPAddresses:    orig.IPAddresses,
		EmailAddresses: orig.EmailAddresses,
		URIs:           orig.URIs,
	}
	der, err := x509.CreateCertificateRequest(rand.Reader, tmpl, priv)
	if err != nil {
		return nil, err
	}
	return x509.ParseCertificateRequest(der)
}

// ---- response encoding ----------------------------------------------------

// writePKCS7 writes a base64 certs-only PKCS#7 response (RFC 7030 §4.1.3/§4.2.3).
func writePKCS7(w http.ResponseWriter, der []byte) {
	w.Header().Set("Content-Type", "application/pkcs7-mime; smime-type=certs-only")
	w.Header().Set("Content-Transfer-Encoding", "base64")
	w.WriteHeader(http.StatusOK)
	writeBase64(w, der)
}

// writeServerKeygen writes the multipart/mixed serverkeygen response: the
// private key (PKCS#8) followed by the certs-only PKCS#7 (RFC 7030 §4.4.2).
func writeServerKeygen(w http.ResponseWriter, keyDER, certP7 []byte) {
	const boundary = "estServerKeyGenBoundary"
	w.Header().Set("Content-Type", "multipart/mixed; boundary="+boundary)
	w.WriteHeader(http.StatusOK)

	fmt.Fprintf(w, "--%s\r\n", boundary)
	_, _ = io.WriteString(w, "Content-Type: application/pkcs8\r\n")
	_, _ = io.WriteString(w, "Content-Transfer-Encoding: base64\r\n\r\n")
	writeBase64(w, keyDER)
	fmt.Fprintf(w, "\r\n--%s\r\n", boundary)
	_, _ = io.WriteString(w, "Content-Type: application/pkcs7-mime; smime-type=certs-only\r\n")
	_, _ = io.WriteString(w, "Content-Transfer-Encoding: base64\r\n\r\n")
	writeBase64(w, certP7)
	fmt.Fprintf(w, "\r\n--%s--\r\n", boundary)
}

// writeBase64 writes base64 wrapped at 64 columns (RFC 2045 / RFC 7030).
func writeBase64(w io.Writer, data []byte) {
	enc := base64.StdEncoding.EncodeToString(data)
	for len(enc) > 64 {
		_, _ = io.WriteString(w, enc[:64])
		_, _ = io.WriteString(w, "\r\n")
		enc = enc[64:]
	}
	_, _ = io.WriteString(w, enc)
	_, _ = io.WriteString(w, "\r\n")
}
