// Package keycheck implements a fail-closed, dependency-free pre-issuance
// key-quality gate that rejects weak and known-compromised subject public keys,
// as required by CA/Browser Forum Baseline Requirements §6.1.1.3.
//
// It inspects the SubjectPublicKeyInfo a caller is asking the CA to certify —
// never a private key — for:
//
//   - ROCA / CVE-2017-15361: the Infineon RSALib modulus fingerprint. Keys
//     generated by the affected library have a distinctive structure that makes
//     the private key recoverable via Coppersmith's method. Detection is a
//     discrete-logarithm fingerprint test over small primes (no factoring is
//     attempted): a genuine RSALib modulus N satisfies N mod P ∈ ⟨65537⟩ (mod P)
//     for every prime P dividing the generator's primorial, which a random key
//     fails for at least one P with overwhelming probability.
//   - RSA public-exponent policy: reject e < 65537 and even exponents (a valid
//     RSA exponent is odd, and the BRs require at least 65537).
//   - RSA modulus sanity: reject an even modulus and one below the minimum bit
//     length (2048 by default), independent of the certificate-lint size rule.
//   - Debian OpenSSL weak keys (CVE-2008-0166): membership in an operator-supplied
//     blocklist of known-weak fingerprints (see Blocklist; no blob is vendored).
//
// The operator-managed compromised-key blocklist (a persisted store keyed by the
// SubjectPublicKeyInfo SHA-256 fingerprint) and duplicate-subject-key detection
// are layered on top by the ca package, which owns the persistence; this package
// is intentionally pure so it is trivially testable and runs identically on every
// issuance surface (REST/ACME/EST/SCEP/CMP/SPIFFE).
package keycheck

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"fmt"
	"math/big"
	"strings"
)

// Finding codes. These are stable identifiers surfaced in audit details, the
// preview verdict, and the per-code Prometheus metric label, so they must not
// change once shipped.
const (
	// CodeROCA marks an RSA modulus matching the Infineon RSALib (CVE-2017-15361)
	// fingerprint.
	CodeROCA = "roca"
	// CodeWeakExponent marks an RSA public exponent below 65537 or even.
	CodeWeakExponent = "weak_exponent"
	// CodeSmallModulus marks an RSA modulus below the configured minimum bit length.
	CodeSmallModulus = "small_modulus"
	// CodeEvenModulus marks an RSA modulus that is even (cannot be a product of two
	// odd primes) — a malformed or maliciously crafted key.
	CodeEvenModulus = "even_modulus"
	// CodeDebianWeakKey marks a key whose fingerprint is in the loaded Debian
	// OpenSSL weak-key blocklist (CVE-2008-0166).
	CodeDebianWeakKey = "debian_weak_key"
	// CodeBlockedKey marks a key in the operator-managed compromised-key blocklist.
	// It is added by the ca package (which owns the persisted store), not by Inspect.
	CodeBlockedKey = "blocked_key"
	// CodeDuplicateKey marks a subject public key already certified for a different
	// subject. It is added by the ca package (which owns the inventory), not by Inspect.
	CodeDuplicateKey = "duplicate_key"
)

// Finding is one key-quality defect discovered on a candidate public key.
type Finding struct {
	// Code is one of the Code* constants above.
	Code string `json:"code"`
	// Detail is a human-readable explanation of the specific defect.
	Detail string `json:"detail"`
}

// Result is the outcome of inspecting one candidate subject public key. A Result
// with no findings is a pass.
type Result struct {
	// Findings lists every key-quality defect discovered, in check order.
	Findings []Finding `json:"findings,omitempty"`
	// Fingerprint is the SubjectPublicKeyInfo fingerprint of the inspected key
	// ("SHA256:<base64>"), or "" when the key could not be marshaled. It is the
	// same textual form as an OpenSSH SHA-256 fingerprint and the key against which
	// the operator compromised-key blocklist is stored.
	Fingerprint string `json:"fingerprint,omitempty"`
}

// OK reports whether the key passed every check (no findings).
func (r Result) OK() bool { return len(r.Findings) == 0 }

// Add appends a finding. It is exported so the ca package can fold in the
// persisted-blocklist and duplicate-subject-key findings it owns, keeping a
// single combined Result per key.
func (r *Result) Add(code, detail string) {
	r.Findings = append(r.Findings, Finding{Code: code, Detail: detail})
}

// Codes returns the finding codes in order (for compact logging/metrics).
func (r Result) Codes() []string {
	out := make([]string, 0, len(r.Findings))
	for _, f := range r.Findings {
		out = append(out, f.Code)
	}
	return out
}

// Summary renders a one-line description of the findings for audit details.
func (r Result) Summary() string {
	if r.OK() {
		return "key check: ok"
	}
	parts := make([]string, 0, len(r.Findings))
	for _, f := range r.Findings {
		parts = append(parts, f.Code)
	}
	return fmt.Sprintf("key check: %d finding(s): %s", len(r.Findings), strings.Join(parts, ", "))
}

// Policy selects which stateless structural checks Inspect runs. The zero value
// runs nothing; use DefaultPolicy for the standard fail-closed check set.
type Policy struct {
	// CheckROCA enables the CVE-2017-15361 fingerprint test on RSA moduli.
	CheckROCA bool
	// CheckExponent enables the RSA public-exponent policy (e >= 65537, odd).
	CheckExponent bool
	// CheckModulus enables the RSA modulus sanity checks (odd, minimum bit length).
	CheckModulus bool
	// MinRSABits is the minimum RSA modulus bit length. Zero uses DefaultMinRSABits.
	MinRSABits int
	// Blocklist, when non-nil, is consulted for Debian OpenSSL weak-key membership.
	Blocklist *Blocklist
}

// DefaultMinRSABits is the minimum RSA modulus bit length enforced when a policy
// does not specify one (NIST SP 800-57 / CA-Browser Forum floor).
const DefaultMinRSABits = 2048

// DefaultPolicy returns the standard structural check set: ROCA, exponent, and
// modulus checks all on, with the given (optional) Debian blocklist.
func DefaultPolicy(blocklist *Blocklist) Policy {
	return Policy{
		CheckROCA:     true,
		CheckExponent: true,
		CheckModulus:  true,
		MinRSABits:    DefaultMinRSABits,
		Blocklist:     blocklist,
	}
}

// Inspect runs the enabled stateless checks against a candidate subject public
// key and returns the findings (empty == pass). It never returns an error: an
// unmarshalable key simply yields an empty Fingerprint (and no structural
// findings for a key type it cannot reason about). It performs no I/O and mutates
// nothing, so it is safe on every issuance surface and in the dry-run preview.
func Inspect(pub crypto.PublicKey, pol Policy) Result {
	var res Result
	if fp, err := Fingerprint(pub); err == nil {
		res.Fingerprint = fp
	}
	switch k := pub.(type) {
	case *rsa.PublicKey:
		inspectRSA(&res, k, pol)
	case *ecdsa.PublicKey, ed25519.PublicKey, ed25519.PrivateKey:
		// ROCA / exponent / modulus checks are RSA-specific. EC and Ed25519 keys are
		// only subject to the blocklist(s) below.
	default:
		// An unknown classical key type has nothing structural to inspect; the
		// blocklist checks (which operate on the marshaled SPKI) still apply.
	}
	if pol.Blocklist != nil && res.Fingerprint != "" && pol.Blocklist.Contains(pub) {
		res.Add(CodeDebianWeakKey, "public key fingerprint is present in the weak-key (Debian OpenSSL / CVE-2008-0166) blocklist")
	}
	return res
}

// inspectRSA applies the RSA-specific structural checks.
func inspectRSA(res *Result, k *rsa.PublicKey, pol Policy) {
	n := k.N
	if pol.CheckModulus {
		switch {
		case n == nil || n.Sign() <= 0:
			res.Add(CodeEvenModulus, "RSA modulus is missing or not a positive integer")
			return
		default:
			min := pol.MinRSABits
			if min <= 0 {
				min = DefaultMinRSABits
			}
			if n.BitLen() < min {
				res.Add(CodeSmallModulus, fmt.Sprintf("RSA modulus is %d bits, below the %d-bit minimum", n.BitLen(), min))
			}
			if n.Bit(0) == 0 {
				res.Add(CodeEvenModulus, "RSA modulus is even, so it cannot be a product of two odd primes")
			}
		}
	}
	if pol.CheckExponent {
		switch e := k.E; {
		case e < 65537:
			res.Add(CodeWeakExponent, fmt.Sprintf("RSA public exponent %d is below the required minimum of 65537", e))
		case e%2 == 0:
			res.Add(CodeWeakExponent, fmt.Sprintf("RSA public exponent %d is even; a valid RSA exponent must be odd", e))
		}
	}
	if pol.CheckROCA && n != nil && n.Sign() > 0 {
		if IsROCAVulnerable(n) {
			res.Add(CodeROCA, "RSA modulus matches the Infineon RSALib fingerprint (ROCA / CVE-2017-15361); the private key may be practically recoverable")
		}
	}
}

// Fingerprint returns the SubjectPublicKeyInfo fingerprint of a public key as
// "SHA256:<base64>" — the same textual form as an OpenSSH SHA-256 fingerprint
// (base64, standard alphabet, no padding), computed over the DER-encoded
// SubjectPublicKeyInfo. This is the canonical key against which the operator
// compromised-key blocklist and duplicate-subject-key detection are stored.
func Fingerprint(pub crypto.PublicKey) (string, error) {
	spki, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(spki)
	return "SHA256:" + base64.RawStdEncoding.EncodeToString(sum[:]), nil
}

// --- ROCA / CVE-2017-15361 fingerprint detection ---

// rocaPrimes are the small primes used for the ROCA discrete-logarithm
// fingerprint test: the first 38 primes after 2 (3..167). The affected Infineon
// RSALib generates each prime factor as p = k·M + (65537^a mod M) where M is the
// primorial of the smallest primes (which, for every supported key size, includes
// all of these), so for every prime P here a genuine modulus N = p·q satisfies
// N ≡ 65537^(a+b) (mod P) — i.e. N mod P lies in the multiplicative subgroup
// generated by 65537 modulo P. The masks below encode those subgroups.
var rocaPrimes = []int64{
	3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73,
	79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
}

// rocaMasks[i] has bit r set iff r is in the subgroup ⟨65537⟩ modulo rocaPrimes[i].
// It is derived from the generator at init, not hand-transcribed, so it cannot
// drift from the mathematics.
var rocaMasks = buildROCAMasks()

func buildROCAMasks() []*big.Int {
	gen := big.NewInt(65537)
	masks := make([]*big.Int, len(rocaPrimes))
	for i, p := range rocaPrimes {
		P := big.NewInt(p)
		mask := new(big.Int)
		g := new(big.Int).Mod(gen, P)
		cur := big.NewInt(1) // 65537^0 mod P
		seen := make(map[int64]bool)
		for {
			r := new(big.Int).Mod(cur, P).Int64()
			if seen[r] {
				break
			}
			seen[r] = true
			mask.SetBit(mask, int(r), 1)
			cur.Mul(cur, g)
			cur.Mod(cur, P)
		}
		masks[i] = mask
	}
	return masks
}

// IsROCAVulnerable reports whether an RSA modulus carries the Infineon RSALib
// (ROCA / CVE-2017-15361) fingerprint. It is a probabilistic structural test: a
// genuine RSALib modulus is always flagged, and a random modulus is flagged only
// with negligible probability (the discriminating primes shrink the accepted
// residue set to a tiny fraction). No factoring is performed.
func IsROCAVulnerable(n *big.Int) bool {
	if n == nil || n.Sign() <= 0 {
		return false
	}
	rem := new(big.Int)
	for i, p := range rocaPrimes {
		rem.Mod(n, big.NewInt(p))
		if rocaMasks[i].Bit(int(rem.Int64())) == 0 {
			return false
		}
	}
	return true
}
