package database

import (
	"crypto/rand"
	"database/sql"
	"fmt"
	"time"
)

// nonceSecretName is the fixed key of the singleton row in acme_nonce_secret.
// A named key (rather than a fixed id) lets GetOrCreateACMENonceSecret use the
// portable INSERT-if-absent helper for its race-safe create.
const nonceSecretName = "default"

// nonceSecretLen is the size of a freshly generated nonce-signing secret. 32
// bytes matches the HMAC-SHA256 block/key size and provides ample entropy.
const nonceSecretLen = 32

// GetOrCreateACMENonceSecret returns the server-wide secret used to sign
// self-authenticating ACME anti-replay nonces, generating a fresh random one on
// first use. The secret lives in the shared store, so every replica reading it
// agrees on one key and can verify nonces minted by any other replica.
//
// It is race-safe across replicas: the create is an insert-if-absent followed by
// a read, so two replicas starting simultaneously converge on whichever value
// won the insert (the loser's generated bytes are discarded, never returned).
func (db *DB) GetOrCreateACMENonceSecret() ([]byte, error) {
	// Fast path: the secret already exists (the common case after first startup).
	if secret, err := db.readNonceSecret(); err == nil {
		return secret, nil
	} else if err != sql.ErrNoRows {
		return nil, fmt.Errorf("reading acme nonce secret: %w", err)
	}

	// Generate a candidate and try to claim the row. ON CONFLICT DO NOTHING means
	// a concurrent replica that inserted first keeps its value; ours is dropped.
	gen := make([]byte, nonceSecretLen)
	if _, err := rand.Read(gen); err != nil {
		return nil, fmt.Errorf("generating acme nonce secret: %w", err)
	}
	if _, err := db.exec(
		db.insertOrIgnore("acme_nonce_secret", "name, secret, created_at", "?, ?, ?"),
		nonceSecretName, gen, time.Now().UTC(),
	); err != nil {
		return nil, fmt.Errorf("inserting acme nonce secret: %w", err)
	}

	// Re-read so we return the authoritative value — ours if we won the insert,
	// the winner's otherwise.
	secret, err := db.readNonceSecret()
	if err != nil {
		return nil, fmt.Errorf("re-reading acme nonce secret: %w", err)
	}
	return secret, nil
}

// readNonceSecret loads the stored nonce secret, returning sql.ErrNoRows when it
// has not been created yet.
func (db *DB) readNonceSecret() ([]byte, error) {
	var secret []byte
	err := db.queryRow(`SELECT secret FROM acme_nonce_secret WHERE name = ?`, nonceSecretName).Scan(&secret)
	if err != nil {
		return nil, err
	}
	return secret, nil
}

// ConsumeACMENonce atomically records a nonce as consumed and reports whether
// this was its first use. The insert is the single durable write on the ACME
// nonce path: it succeeds (returning true) the first time a nonce is spent and
// no-ops on the primary-key conflict (returning false) for any later replay,
// regardless of which replica handled the original request. expiresAt bounds how
// long the record is retained so the background GC can prune it.
func (db *DB) ConsumeACMENonce(nonceHash string, expiresAt time.Time) (bool, error) {
	res, err := db.exec(
		db.insertOrIgnore("acme_nonces", "nonce_hash, expires_at", "?, ?"),
		nonceHash, expiresAt.UTC(),
	)
	if err != nil {
		return false, err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return false, err
	}
	// One row inserted → first use; zero rows (conflict) → replay.
	return n > 0, nil
}

// GCACMENonces deletes consumed-nonce records that have passed their expiry and
// reports how many were removed. It is idempotent and safe to run on every
// replica: an expired nonce is rejected by its embedded-timestamp check before
// the consumed-set is consulted, so a pruned record can never let a replay slip
// through.
func (db *DB) GCACMENonces(now time.Time) (int64, error) {
	res, err := db.exec(`DELETE FROM acme_nonces WHERE expires_at < ?`, now.UTC())
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
